### ISSUE TITLE
rioprevmain not working

### ISSUE THREAD

**Issue by mechiah** [0xbs/premade-groups-filter#100]
Good morning, I think rioprevmain stopped working. Whittled my expression down and to that to see what was breaking, and copy/pasted expression from your wiki to make sure I wasn't dealing with a typo.

![image](https://user-images.githubusercontent.com/44839576/187028809-7122ce3a-70ac-42b1-9d6d-91755dbfb5a2.png)

**Comment by 0xbs** [comment]
Thank you for the report. Unfortunately the documentation is wrong, it is `riomainprev` (and not `rioprevmain`). I updated the documentation.
