### ISSUE TITLE
Again ... Dialog.lua:66 .. Again ... Again >_<

### ISSUE THREAD

**Issue by Hollicsh** [0xbs/premade-groups-filter#110]
2x ...terface/AddOns/PremadeGroupsFilter/Dialog/Dialog.lua:66: attempt to index local 'model' (a nil value)
[string "@Interface/AddOns/PremadeGroupsFilter/Dialog/Dialog.lua"]:66: in function <...terface/AddOns/PremadeGroupsFilter/Dialog/Dialog.lua:63>

Locals:
self = UsePFGButton {
 0 = <userdata>
 isSkinned = true
 SetHighlightTexture = <function> defined =[C]:-1
 SetPushedTexture = <function> defined =[C]:-1
 Text = UsePFGButtonText {
 }
 text = UsePFGButtonText {
 }
 Backdrop = Frame {
 }
 SetNormalTexture = <function> defined =[C]:-1
}
button = "LeftButton"
down = false
checked = true
model = nil
(*temporary) = nil
(*temporary) = 2
(*temporary) = "attempt to index local 'model' (a nil value)"
PGF = <table> {
 PopupMenu_Toggle = <function> defined @Interface/AddOns/PremadeGroupsFilter/Dialog/PopupMenu.lua:127
 GetModel = <function> defined @Interface/AddOns/PremadeGroupsFilter/Main.lua:80
 Dialog_ResetPosition = <function> defined =[C]:-1
 Dialog_SetUpMinMaxField = <function> defined @Interface/AddOns/PremadeGroupsFilter/Dialog/Setup.lua:188
 GameTooltip_AddWhite = <function> defined @Interface/AddOns/PremadeGroupsFilter/Dialog/Help.lua:45
 ResetSearchEntries = <function> defined @Interface/AddOns/PremadeGroupsFilter/Main.lua:33
 previousSearchExpression = ""
 AddRoleIndicators = <function> defined @Interface/AddOns/PremadeGroupsFilter/Modules/RoleIndicators.lua:70
 GetLockoutInfo = <function> defined @Interface/AddOns/PremadeGroupsFilter/Modules/Lockout.lua:40
 Empty = <function> defined @Interface/AddOns/PremadeGroupsFilter/Modules/Util.lua:102
 UsePFGButton = UsePFGButton {
 }
 MigrateStateV2 = <function> defined @Interface/AddOns/PremadeGroupsFilter/Init.lua:178
 Table_Copy_Shallow = <function> defined @Interface/AddOns/PremadeGroupsFilter/Modules/Util.lua:36
 GetExpressionFromAdvancedExpression = <function> defined @Interface/AddOns/PremadeGroupsFilter/Main.lua:60
 Table_Subtract = <function> defined @Interface/AddOns/PremadeGroupsFilter/Modules/Util.lua:57
 Dialog_Max_OnTabPressed = <function> defined @Interface/AddOns/PremadeGroupsFilter/Dialog/Dialog.lua:190
 GetPlayerInfo = <function> defined @Interface/AddOns/PremadeGroupsFilter/Modules/PlayerInfo.lua:74
 declinedGroups = <table> {
 }
 DoesPassThroughFilter = <function> defined @Interface/AddOns/PremadeGroupsFilter/Modules/Expression.lua:46
 previousSearchLeaders = <table> {
 }
 HasRemainingSlotsForLocalPlayerPartyRoles = <function> defined @Interface/AddOns/PremadeGroupsFilter/Main.lua:164
 GetPvPScoreRarityColorByTier = <function> defined @Interface/AddOns/PremadeGroupsFilter/Modules/RatingInfo.lua:25
 String_TrimWhitespace = <function> defined @Interface/AddOns/PremadeGroupsFilter/Modules/Util.lua:89
 Dialog_Min_OnTabPressed = <function> defined @Interface/AddOns/PremadeGroupsFilter/Dialog/Dialog.lua:186
 ratingInfoFrames = <table> {
 }
 Dialog_DifficultyDropdown_OnClick = <function> defined @Interface/AddOns/PremadeGroupsFilter/Dialog/Dialog.lua:175
 PutRaiderIOAliases = <function> defined @Interface/AddOns/PremadeGroupsFilter/Main.lua:575
 Dialog_SortingExpression_OnTextChanged = <function> defined @Interface/AddOns/PremadeGroupsFilter/Dialog/Dialog.lua:120
 Dialog_ResetButton_OnClick = <function> defined @Interface/AddOns/PremadeGroupsFilter/Dialog/Dialog.lua:165
 Dialog_OnMouseUp = <function> defined @Interface/AddOns/PremadeGroupsFilter/Dialog/Setup.lua:69
 Dialog_OnMouseDown = <function> defined @Interface/AddOns/PremadeGroupsFilter/Dialog/Setup.lua:64
 Dialog_Reset = <function> defined @Interface/AddOns/PremadeGroupsFilter/Dialog/Dialog.lua:138
 Dialog_ResetMinMaxField = <function> defined @Interface/AddOns/PremadeGroupsFilter/Dialog/Dialog.lua:130
 RemoveCommentLines = <function> defined @Interface/AddOns/PremadeGroupsFilter/Main.lua:70
 PopupMenu_Register = <function> defined @Interface/AddOns/PremadeGroupsFilter/Dialog/PopupMenu.lua:32
 Dialog_MinMax_OnTextChanged = <function> defined @Interface/AddOns/PremadeGroupsFilter/Dialog/Dialog.lua:100
 GetDifficulty = <function> defined @Interface/AddOns/PremadeGroupsFilter/Modules/Difficulty.lua:376
 Dialog_ResetGenericField = <function> defined @Interface/AddOns/PremadeGroupsFilter/Dialog/Dialog.lua:96
 IsMostLikelySameInstance = <function> defined @Interface/AddOns/PremadeGroupsFilter/Modules/Util.lua:127
 Dialog_ToggleCheckboxAccordingToMinMaxFields = <f

**Comment by 0xbs** [comment]
Which tab did you open? From the stack traces it looks like it could not find out which tab you actually opened. Is this a permanent error on this tab? Or other tabs as well?

**Comment by 0xbs** [comment]
Also, if you encounter the error, could you dump the following information while the group finder window is still open?

```
/dump PVEFrame.activeTabIndex
/dump LFGListFrame.SearchPanel.categoryID
/dump LFGListFrame.CategorySelection.selectedCategory
/dump LFGListFrame.SearchPanel.filters
/dump LFGListFrame.CategorySelection.selectedFilters
```

**Comment by Hollicsh** [comment]
I press "search for a group", then I press "pre-assembled groups", then I press "dungeons", everything is as usual.
Sometimes it happens that the checkbox is inactive and you have to activate it manually, hence the error occurs.

![Screenshot_1](https://user-images.githubusercontent.com/54585769/198884189-60c59cab-f802-4a14-b839-f28b23deb4f6.png)
![Screenshot_2](https://user-images.githubusercontent.com/54585769/198884192-0709dbb2-4404-4149-8999-f701d7b41804.png)

**Comment by Hollicsh** [comment]
> Also, if you encounter the error, could you dump the following information while the group finder window is still open?
> 
> ```
> /dump PVEFrame.activeTabIndex
> /dump LFGListFrame.SearchPanel.categoryID
> /dump LFGListFrame.CategorySelection.selectedCategory
> /dump LFGListFrame.SearchPanel.filters
> /dump LFGListFrame.CategorySelection.selectedFilters
> ```

As soon as I encounter this error again, I will definitely let you know.

**Comment by Hollicsh** [comment]
Was it necessary to enter into the chat one command at a time ?

If yes, then here:
[20:07:17] Dump: value=PVEFrame.activeTabIndex 
[20:07:17] empty result 
[20:07:23] Dump: value=LFGListFrame.SearchPanel.categoryID 
[20:07:23] [1]=2 
[20:07:28] Dump: value=LFGListFrame.CategorySelection.selectedCategory 
[20:07:28] [1]=2 
[20:07:34] Dump: value=LFGListFrame.SearchPanel.filters 
[20:07:34] [1]=0 
[20:07:39] Dump: value=LFGListFrame.CategorySelection.selectedFilters 
[20:07:39] [1]=0

**Comment by 0xbs** [comment]
One at a time, as you did. Thank you!

The issue is that `PVEFrame.activeTabIndex` is `nil` but it should not be. The configuration is stored by tab (PvE or PvP), category (quests, dungeons, arena, ...) and filters (SL raids, other raids). Whenever you open a search, it loads the corresponding configuration. However, if the tab index is nil, it does not know what tab you're on. I suspected a timing issue, but in this case the dump should have shown a result. So something prevents the tab index from being set correctly and still does not mess up the group search. I will investigate in a few days if I can find the reason or another source of the tab index.

**Comment by Hollicsh** [comment]
Perhaps the problem is in ElvUI ?
Because I use ElvUI.

**Comment by 0xbs** [comment]
Ah yes, looks like the same error as in #53. But we now know what went wrong. Will try to see if I can find the issue.

**Comment by 0xbs** [comment]
Could the bug be related to being AFK?

1. Open group finder
2. Wait until AFK
3. Cancel AFK by e.g. moving
4. Try to use the premade dungeon search

The reason why I suspect this is that ElvUI is calling `PVEFrame_ToggleFrame` [here](https://github.com/tukui-org/ElvUI/blob/c6cbd62bf5d8d6ae87943e602d0b9ceae55fa7d9/ElvUI/Core/Modules/Misc/AFK.lua#L112) without any arguments twice after you return from AFK. The comment even states that there is a bug involved. Could you please do a test with being AFK first?

**Comment by Hollicsh** [comment]
I tried to do everything as you suggested. After returning from afk, the checkbox automatically turned on and the addon turned on itself.

**Comment by 0xbs** [comment]
Thank you. So it's not the AFK mode, at least not reproducible. There is more code related to the group finder in ElvUI, maybe the bug is somewhere in there.

**Comment by Hollicsh** [comment]
Interesting fact: when I press on the letter "I", then click on "Premade groups", the addon works correctly and the checkbox is already checked.
But when I click on "Group Search", then click on "Premade Groups", the addon appears to be disabled and the check mark is not there.

What the fuck ...

**Comment by 0xbs** [comment]
Could you post a screenshot where you click to get the error? It is the micro button bar (char, spell book, talents, achievments, quests, guild, **group search**, collections, guide, shop, menu)? Or another button?
When I mouse click the group search button in the micro button bar (without ElvUI), everything works as expected.

**Comment by 0xbs** [comment]
Could you please also post a list of your addons? It might not be ElvUI but another addon.

**Comment by Hollicsh** [comment]
> Could you post a screenshot where you click to get the error? It is the micro button bar (char, spell book, talents, achievments, quests, guild, **group search**, collections, guide, shop, menu)? Or another button? When I mouse click the group search button in the micro button bar (without ElvUI), everything works as expected.


![Screenshot_2](https://user-images.githubusercontent.com/54585769/200173717-328e98e5-97db-4db9-a41e-7026bf0c9d92.png)

**Comment by Hollicsh** [comment]
> Could you please also post a list of your addons? It might not be ElvUI but another addon.

DBM, Details, HandyNotes, ElvUI (general ElvUI and ProjectAzilroka and AddonSkins and Shadow and Light), WeakAuras, VenturePlan, SavedInstances, Rarity, RareScanner, Raider.io, Mythic Dungeon Tools, Postal, OmniCC, BtWQuests.

**Comment by 0xbs** [comment]
Having DBM, Details, HandyNotes, WeakAuras, VenturePlan, Raider.io, Mythic Dungeon Tools, Postal myself, I think they are fine. That leaves ElvUI, ElvUI S&L, Project Azilroka, Rarity, RareScanner, OmniCC, BtWQuests. In #53 Sifuedition claims that Project Azilroka is causing it, but I did not find anything relevant in the code. Can you confirm that? So if you disable Azilroka, is the problem gone? Does it still happen without any addons or just with ElvUI?

On my PTR installation, I deleted the WTF folder to reset all options, deleted all addons, and installed PGF, ElvUI, ElvUI S&S and Project Azilroka. I did not get any errors when clicking the group finder button with the mouse. I tried multiple things but never got an error. That leaves me a bit helpless.

**Comment by Hollicsh** [comment]
The problem was solved by resetting all data !
Thank u !
