### ISSUE TITLE
Options Pane Blank

### ISSUE THREAD

**Issue by Yngwiemalmst** [0xbs/premade-groups-filter#111]
I want to hide the role icons but the options pane is blank

![image](https://user-images.githubusercontent.com/118015940/201420807-9f27111d-237b-4451-bc8a-aa2216ea58c5.png)

**Comment by 0xbs** [comment]
Empty options pane most likely means that a Lua error occurred when loading the options.

Do you see any Lua errors related to PGF in BugSack? 

Also have you tried reinstalling and resetting the addon's settings files (can be done via CurseForge Client or by deleting the corresponding files in the WTF folder)?

**Comment by Yngwiemalmst** [comment]
Thanks for the reply, I didn't have any LUA errors for this addon and deleting/reinstalling did not work.

It worked again after I deleted/disabled a few other addons with LUA errors. I also had to click Premade Groups filter, then click a different addon, then click premade again for it to show up.
