### ISSUE TITLE
Option to skip Role/Note prompt on One-click signup

### ISSUE THREAD

**Issue by Taizunz** [0xbs/premade-groups-filter#123]
First off, thanks for adding this feature in the first place a few days ago - another addon I use used to have this feature as well, but unfortunately it broke with the DF pre-patch and hasn't been fixed/readded. So thanks for adding it!

My request is about this prompt in particular:
![image](https://user-images.githubusercontent.com/15648000/202476708-fddb86f2-9354-49c8-9090-a7434ab3f394.png)

Having an option to skip that prompt entirely and immediately sign-up to the group when clicking on the group would be fantastic.

**Comment by 0xbs** [comment]
Added a new option in version 3.3.3 to skip the dialog :)

**Comment by Taizunz** [comment]
You're the best! Thanks!
