### ISSUE TITLE
Option to disable/comment out lines in a search string

### ISSUE THREAD

**Issue by LordBoos** [0xbs/premade-groups-filter#126]
I'd like to have an option to somehow disable/comment out lines in the search string.
Eg. I search for something like:
```
partyfit
and (tanks == 1 or heals == 1)
and (gd or yard or gmbt)
```
But when I want to see all dungeons I have to delete the last line. I'd like to do something like this to "disable" the line:
```
partyfit
and (tanks == 1 or heals == 1)
#and (gd or yard or gmbt)
```

**Comment by 0xbs** [comment]
Since you are actually writing a Lua expression evaluating to a boolean, you may simply use [Lua comments](https://www.lua.org/pil/1.3.html):

```Lua
partyfit
and (tanks == 1 or heals == 1)
--and (gd or yard or gmbt)
```

Or even inbetween:
```Lua
tanks == 1 --[[ and heals == 1 ]] and dps == 3
```
