### ISSUE TITLE
Currently signed up groups at top

### ISSUE THREAD

**Issue by azmanomer** [0xbs/premade-groups-filter#129]
Hello first of all thank you for the beatiful addon. Can you please also add option to show currently signed up groups at top so we can cancel or see the groups changes since we got 5 sign up limit. I tried it by myself but I can not do showing them while sorting by age :(

**Comment by 0xbs** [comment]
Groups you applied to are now sorted to the top by default.

You may do the same in advanced mode using a sorting expression like `appduration desc, mprating desc`

**Comment by SamK132** [comment]
How dies it work?

**Comment by 0xbs** [comment]
How does what work? Advanced mode? Click the button next to the close button (the make-smaller-button) to enter advanced mode. You can enter a custom filter and sorting expression there.

**Comment by SamK132** [comment]
Hey, so I tried to test this on me and unfortunately they are not sorted to the top

**Comment by WybeBosch** [comment]
Hey man, i was trying to make this work but it aint working? 
![image](https://user-images.githubusercontent.com/40889930/210135174-53a9ed26-e4f2-4c19-afeb-0a3585800e65.png)
Am i doing something wrong?
