### ISSUE TITLE
GetApplicationInfo(resultID) Error

### ISSUE THREAD

**Issue by ljlevend** [0xbs/premade-groups-filter#131]
I get this error in game when moving the mouse over a listing in the Dungeon groups list.
```
Message: Interface/AddOns/PremadeGroupsFilter/Main.lua:206: Usage: GetApplicationInfo(resultID)
Time: Tue Dec 20 20:31:02 2022
Count: 1
Stack: Interface/AddOns/PremadeGroupsFilter/Main.lua:206: Usage: GetApplicationInfo(resultID)
[string "=[C]"]: in function `?'
[string "@Interface/AddOns/PremadeGroupsFilter/Main.lua"]:581: in function <Interface/AddOns/PremadeGroupsFilter/Main.lua:319>
[string "=[C]"]: ?
[string "=[C]"]: in function `LFGListUtil_SortSearchResults'
[string "@Interface/FrameXML/LFGList.lua"]:2125: in function `LFGListSearchPanel_UpdateResultList'
[string "@Interface/FrameXML/LFGList.lua"]:2033: in function `onEvent'
[string "@Interface/FrameXML/LFGList.lua"]:218: in function <Interface/FrameXML/LFGList.lua:139>

Locals: (*temporary) = <table> {
 1 = 893
 2 = 887
 3 = 890
 4 = 894
 5 = 896
 6 = 892
 7 = 885
 8 = 897
}
(*temporary) = <function> defined @Interface/AddOns/PremadeGroupsFilter/Main.lua:132
(*temporary) = 885
(*temporary) = 887
(*temporary) = nil
```

**Comment by 0xbs** [comment]
From the stacktrace, it looks like the error did not occur on hovering with the mouse but when doing a search or applying to a group. 

1. Are you sure you get an error when just hovering over an entry? If yes, is this really the exact error?
2. Do you get a error on every list entry or just some of them?
3. Do you get an error on arbitrary searches or just sometimes on specific search results?
4. Do you get an error with just PGF and no other addon installed?

**Comment by ljlevend** [comment]
Sorry, I could be wrong about the error occur on hovering with the mouse. Lets assume that you are correct about it occurring when doing a search or applying to a group. I will pay closer attention to the specific conditions that cause this issue to occur and update you if I have more information. Thanks.

**Comment by 0xbs** [comment]
Do you have ElvUI installed? [ElvUI bug #539](https://github.com/tukui-org/ElvUI/issues/539) is sometimes incorrectly being reported as a PGF bug.

**Comment by ljlevend** [comment]
I do not have ElvUI installed. The error occurs when I click the "Sign Up" button, not when I hover over a group as I initially reported (sorry about that). So far the error has only occurred after I click the "Sign Up" button while I already have at least two pending requests to join a group.

**Comment by fubaWoW** [comment]
same here
```LUA
6x PremadeGroupsFilter/Main.lua:206: Usage: GetApplicationInfo(resultID)
[string "=[C]"]: in function `GetApplicationInfo'
[string "@PremadeGroupsFilter/Main.lua"]:206: in function <PremadeGroupsFilter/Main.lua:203>
[string "=(tail call)"]: ?
[string "=[C]"]: in function `?'
[string "@PremadeGroupsFilter/Main.lua"]:581: in function <PremadeGroupsFilter/Main.lua:319>
[string "=[C]"]: in function `LFGListUtil_SortSearchResults'
[string "@FrameXML/LFGList.lua"]:2125: in function `LFGListSearchPanel_UpdateResultList'
[string "@FrameXML/LFGList.lua"]:2033: in function `onEvent'
[string "@FrameXML/LFGList.lua"]:218: in function <FrameXML/LFGList.lua:139>

Locals:
(*temporary) = nil

```
happens when "sign up" multiple groups at the same time, over and over again

**Comment by 0xbs** [comment]
Would be interesting to know the exact cause. From your report is looks like the second ID is either nil or not a number.

My fix would be
```
    if not searchResultID1 or type(searchResultID1) ~= "number" then return false end
    if not searchResultID2 or type(searchResultID2) ~= "number" then return true end
```
at the top of the function SortByFriendsAndAge

**Comment by fubaWoW** [comment]
> Would be interesting to know the exact cause. From your report is looks like the second ID is either nil or not a number.
yeah it's definitely the "searchResultID2"
i will test it further today

**Comment by 0xbs** [comment]
I did some runs over the holidays but never got the error. Not sure what's different on my machine, maybe different set of other addons.

**Comment by fubaWoW** [comment]
> I did some runs over the holidays but never got the error. Not sure what's different on my machine, maybe different set of other addons.

I did also some runs now BUT just solo last days and also had no errors yet and i did not change any of my addons (fix included!)  
  
But i remember the error happend if i queue as a group, maybe this is the reason?!
Im gonna try to test this next days and will report back.

**Comment by ljlevend** [comment]
Good find. I've always been in a party with my friend when I sign up for a group so that could be related to the issue.

**Comment by fubaWoW** [comment]
Got another Error today with "your fix" active -> Invalid Sorting:

You need to Queue a Listed Group but your Group need 2+ Players who are already in Group and the error occurs if the Listed Group accept your group to join!

And as we already Expected the ``searchResultID2`` is ``nil`` at this time -> this cause the error
so ``searchResultID2`` needs an error check or better both of them 1 and 2

```LUA
2x PremadeGroupsFilter/Main.lua:594: invalid order function for sorting
[string "=[C]"]: in function `?'
[string "@PremadeGroupsFilter/Main.lua"]:594: in function <PremadeGroupsFilter/Main.lua:332>
[string "=[C]"]: in function `LFGListUtil_SortSearchResults'
[string "@FrameXML/LFGList.lua"]:2125: in function `LFGListSearchPanel_UpdateResultList'
[string "@FrameXML/LFGList.lua"]:2033: in function `onEvent'
[string "@FrameXML/LFGList.lua"]:218: in function <FrameXML/LFGList.lua:139>

Locals:
(*temporary) = <table> {
 1 = 2045
 2 = 2034
 3 = 2059
 4 = 2019
 5 = 2083
}
(*temporary) = <function> defined @PremadeGroupsFilter/Main.lua:132
(*temporary) = 2019
(*temporary) = 2034
(*temporary) = nil
```

**Comment by fubaWoW** [comment]
it's not fixed with this ^^
as i already said, i got **this** Error **WHILE** the "fix" was in the ``SortByFriendsAndAge`` function!
:
```
2x PremadeGroupsFilter/Main.lua:594: invalid order function for sorting
[string "=[C]"]: in function `?'
[string "@PremadeGroupsFilter/Main.lua"]:594: in function <PremadeGroupsFilter/Main.lua:332>
[string "=[C]"]: in function `LFGListUtil_SortSearchResults'
[string "@FrameXML/LFGList.lua"]:2125: in function `LFGListSearchPanel_UpdateResultList'
[string "@FrameXML/LFGList.lua"]:2033: in function `onEvent'
[string "@FrameXML/LFGList.lua"]:218: in function <FrameXML/LFGList.lua:139>

Locals:
(*temporary) = <table> {
 1 = 2045
 2 = 2034
 3 = 2059
 4 = 2019
 5 = 2083
}
(*temporary) = <function> defined @PremadeGroupsFilter/Main.lua:132
(*temporary) = 2019
(*temporary) = 2034
(*temporary) = nil
```

This is "new" error (as you can see) but this error is caused by the "fix" it seems!
It comes from the ``table.sort(results, PGF.SortByExpression)`` what executes the ``SortByExpression`` what on the other hand executes the ``SortByFriendsAndAge`` -> here we are again, something is wrong there ^^

**Comment by ljlevend** [comment]
I can confirm that the error is not fixed. Do the following to reproduce the issue:
1. Be the leader of a group of 2 players.
2. Sign up to join other groups. For me the issue only occurs after my group has signed up for 2+ groups.

**Comment by 0xbs** [comment]
Thanks for the report, let's continue the discussion on #135 which is the same bug.
