### ISSUE TITLE
ADDON_ACTION_BLOCKED: PremadeGroupsFilter tried to call the protected function 'GetPlaystyleString()'.

### ISSUE THREAD

**Issue by Hndrxuprt** [0xbs/premade-groups-filter#133]
I get this error every time I hover over a group in the LFG
I have installed addon version 3.4.0, tried reinstalling and deleting saved variables from the account and character folders
```
Message: ADDON_ACTION_BLOCKED: PremadeGroupsFilter tried to call the protected function 'GetPlaystyleString()'.
Time: Wed Dec 21 20:51:45 2022
Count: 14
Stack: ADDON_ACTION_BLOCKED: PremadeGroupsFilter tried to call the protected function 'GetPlaystyleString()'.
[string "@Interface/AddOns/ElvUI_Libraries/Core/CallbackHandler-1.0/CallbackHandler-1.0.lua"]:19: in function <...ies/Core/CallbackHandler-1.0/CallbackHandler-1.0.lua:15>
[string "@Interface/AddOns/ElvUI_Libraries/Core/CallbackHandler-1.0/CallbackHandler-1.0.lua"]:54: in function `Fire'
[string "@Interface/AddOns/ElvUI_Libraries/Core/Ace3/AceEvent-3.0/AceEvent-3.0.lua"]:120: in function <...UI_Libraries/Core/Ace3/AceEvent-3.0/AceEvent-3.0.lua:119>
[string "=[C]"]: in function `GetPlaystyleString'
[string "@Interface/FrameXML/LFGList.lua"]:3522: in function <Interface/FrameXML/LFGList.lua:3511>
[string "=[C]"]: ?
[string "=[C]"]: in function `LFGListUtil_SetSearchEntryTooltip'
[string "@Interface/FrameXML/LFGList.lua"]:2597: in function <Interface/FrameXML/LFGList.lua:2594>
[string "=[C]"]: 
```

**Comment by 0xbs** [comment]
This should only happen on accounts that are not fully secured. Have a look at the [corresponding FAQ entry](https://github.com/0xbs/premade-groups-filter/wiki/FAQ#message-will-not-apply-fix-for-interface-action-failed-because-of-an-addon--on-login).

However if your account is fully secured, we have to investigate further. The stacktrace shows that you have ElvUI installed. Does the error still happen if you disable all addon except Premade Groups Filter?

**Comment by Hndrxuprt** [comment]
This error occurs when I enable ElvUI Libraries

**Comment by 0xbs** [comment]
This seems to be [ElvUI bug #539](https://github.com/tukui-org/ElvUI/issues/539) and incorrectly being reported as a PGF bug. This happens quite often, the last addon to touch a bit of code if blaimed even if the real issue is another addon. Closing the bug here.
