### ISSUE TITLE
Adding a key level filter for mythicplus

### ISSUE THREAD

**Issue by jcocca** [0xbs/premade-groups-filter#136]
As long as common groups write the key level in the title, would it be possible to add a filter to select only a specific level or range of level of keystones ?

**Comment by 0xbs** [comment]
Not possible. Since the Battle for Azeroth Prepatch, the group name and comment are protected by Blizzard and can not be evaluated by any addon.

**Comment by yoshimo** [comment]
Maybe something to request upstream then.  The creation is already protected so filtering shouldn't be an issue but rather a nice addition to remove spam

**Comment by 0xbs** [comment]
If you have a contact at Blizzard, go ahead!

It was unprotected before BfA. One of the reasons Blizz added protection was World Quest Group Finder which did automated searches to make world quests easier. I think they overshoot with blocking access to the group title though.
