### ISSUE TITLE
One-click group application

### ISSUE THREAD

**Issue by logforgit** [0xbs/premade-groups-filter#137]
To sign up for a group, you click the group, and then you click "Sign Up". It would be a helpful feature to skip the second step, so that when you click on the group, you immediately apply to it.

* There could be a checkbox/option to enable/disable this feature.
* When enabled, you could perhaps SHIFT-click the group to temporarily disable the feature, so that you could add a note for this specific group application.

**Comment by 0xbs** [comment]
This is literally what is implemented right now. Please check out the addon options in the options panel.
