### ISSUE TITLE
Possible bug - not loading as of 8 Jan update

### ISSUE THREAD

**Issue by Voidrunna** [0xbs/premade-groups-filter#139]
Hi, is it just me or since the update today, it no longer works for me. It's not loading anymore.

**Comment by 0xbs** [comment]
I moved a file in the update, but did not change anything significant.

Not sure what happened, please try reinstalling it. If it still does not load, please reset the settings (via CurseForge client or by deleting the corresponding files in the WTF folder).

You're the first one reporting a bug. Let's wait if someone else has the same issue.

**Comment by Voidrunna** [comment]
Thanks so much, it's working again after reinstalling. Might have been a random error on my side, sorry for the confusion
