### ISSUE TITLE
Filtering specific dungeons can hide 90% of valid results

### ISSUE THREAD

**Issue by AzrethWoW** [0xbs/premade-groups-filter#142]
I have come across this issue numerous times, where more complicated queries that also involve the dungeon name, such as `cos or sbg` or `hov` only show as few as 10% of the valid results. Doing the same query while putting the dungeon name in the Blizzard UI search bar can result in 10x as many results.

There seems to be a bug where the addon filters out completely valid options when the dungeon names are involved. See an example below, the two screenshots were taken just a few seconds apart.

![image](https://user-images.githubusercontent.com/102601302/215854169-1c5f81b6-5ba3-41bf-b4a1-2c054fa12eb3.png)

**Comment by 0xbs** [comment]
https://github.com/0xbs/premade-groups-filter/wiki/FAQ#why-do-i-only-see-a-few-groups-when-filtering-for-multiple-dungeons
