### ISSUE TITLE
The "block" function doesn't always work

### ISSUE THREAD

**Issue by DCCXVIII** [0xbs/premade-groups-filter#146]
The new feature you recently introduced (it's great btw) for some reason does not always work. For whatever reason certain groups are immune to the right-click X button hiding function.

**Comment by 0xbs** [comment]
PGF does not have a feature like that. Do you mean LFGSpamFilter (not by me)? 
LFGSpamFilter: [CurseForge](https://www.curseforge.com/wow/addons/lfgspamfilter), [GitHub](https://github.com/romdeau23/wow-lfgspamfilter)

**Comment by DCCXVIII** [comment]
Ah snap! Sorry I got the addons confused. Yea it's the other addon that has the issue. Ignore this xD
