### ISSUE TITLE
Addon modifies report advertisement functionality 

### ISSUE THREAD

**Issue by NickWSmith** [0xbs/premade-groups-filter#151]
With the addon disabled, in the group finder when you click "report advertisement", it will auto report the listing.

With the addon enabled, you need to go through separate steps to report the advertisement.

**Comment by 0xbs** [comment]
See FAQ: https://github.com/0xbs/premade-groups-filter/wiki/FAQ#report-advertisement-shows-the-report-dialog-instead-of-directly-reporting-the-group
