### ISSUE TITLE
Lock the panel to D&R frame

### ISSUE THREAD

**Issue by p3lim** [0xbs/premade-groups-filter#152]
I keep accidentally moving the filter panel and have to reset it by right-clicking the header. Please add a lock option for it to always be attached.

**Comment by 0xbs** [comment]
I'm also a bit unhappy with the current situation. I will see if I can do something about locking the window. Would a checkbox in the PGF options panel be sufficient for you? I would rather not implement another button in the menu bar, changing the UI is always a major effort.

**Comment by p3lim** [comment]
As long as there is some way to lock it I'm happy.

**Comment by 0xbs** [comment]
Now possible with by setting "Dialog movable" to false in the options panel
