### ISSUE TITLE
Add Keylevel as an option

### ISSUE THREAD

**Issue by oesi94** [0xbs/premade-groups-filter#158]
I always use the advanced epressions, i would like to see to have it possible to add a keylevel range like 22-23. I know i can use it on the normal blizzard search bar, but it would be nice to have it on the addon aswell so i can can have more keylevel ranges.

Example right now;

Blizzard search: 22-23 Addon search: not (cos or sbg or no)

Example for the keylevel option:

(keylevel 22-23 and not (cos or sbg or no)) or (keylevel 24-25 and (cos or sbg or no)

**Comment by 0xbs** [comment]
See #135 or #136
