### ISSUE TITLE
UI Problems

### ISSUE THREAD

**Issue by mosi1981** [0xbs/premade-groups-filter#159]
Since the last update PGF resets some of my UI Settings to Blizz default UI! When I deactivate PGF it is my normal UI. I use NDUI.

**Comment by 0xbs** [comment]
Related to siweia/NDui#240. Code is already fixed in NDUI, so next version should work again.

**Comment by mosi1981** [comment]
Ok thank you for your nice work

Do you mean PGF Version or NDUI?

**Comment by 0xbs** [comment]
Siweia did fix it in NDUI

**Comment by zeenk** [comment]
There also seem to be some overlap issue with [world quest tracker](https://www.curseforge.com/wow/addons/world-quest-tracker) button now after 3.7.2+ update.
[Before with 3.7.1](https://www.curseforge.com/wow/addons/premade-groups-filter/files/4394878)
![2023-03-12_23-26-11](https://user-images.githubusercontent.com/68170439/224577754-e5deb12d-ebc3-47ee-8a2b-b42cfeff3a46.png)

[After with 3.7.2+](https://www.curseforge.com/wow/addons/premade-groups-filter/files/4433498)
![2023-03-12_23-27-57](https://user-images.githubusercontent.com/68170439/224577794-15eb0152-9b46-45ba-ac09-e98a1cc91e50.png)

**Comment by 0xbs** [comment]
Opened a PR to fix the issue on WQT

**Comment by zeenk** [comment]
This bug seems to be back again
![2023-05-15_22-52-16](https://github.com/0xbs/premade-groups-filter/assets/68170439/c9d16b15-8c09-41c5-a649-d5c71838f3de)

**Comment by 0xbs** [comment]
My pull request was never merged by World Quest Tracker. It seems this addon is no longer maintained since two years anyway, is there any reason for you to keep it?

**Comment by zeenk** [comment]
Ah I see, and no I don't really do much world questing anymore so could probably remove it now, but went ahead and applied your PR change to WorldQuestTracker_GroupFinder.lua myself so now that issue is fixed for me again, thx :p

**Comment by 0xbs** [comment]
PR merged, issue should be resolved
