### ISSUE TITLE
Add sorting

### ISSUE THREAD

**Issue by qis** [0xbs/premade-groups-filter#16]
Would it be reasonable to change the syntax to allow sorting based on instance? I'd like to do

```
(kr > tosl > sob) and (dps < 3 or heals==0)
```

instead of

```
(kr or tosl or sob) and (dps < 3 or heals==0)
```

so that KR is listed first, then ToS, then SoB.

**Comment by 0xbs** [comment]
Sorting is now implemented in expert mode.
