### ISSUE TITLE
Settings PGF [empty]

### ISSUE THREAD

**Issue by Hollicsh** [0xbs/premade-groups-filter#162]
Empty settings window o_O
Pressing the setting again displays the settings O_o

![Screenshot_2](https://user-images.githubusercontent.com/54585769/224577740-ffc38061-0907-466e-9030-ddcb68d4935e.png)

**Comment by 0xbs** [comment]
Might be an interference with other addons. Does it happen with only PGF active?

**Comment by Hollicsh** [comment]
Hmmm ...
The problem was in the .lua file o_O
I deleted the .lua file and everything was fine.
