### ISSUE TITLE
Add keyword to check if there's room for bloodlust ("lustfit"?)

### ISSUE THREAD

**Issue by redcatelf** [0xbs/premade-groups-filter#168]
If I were to apply to the following group as a resto druid, it would leave no space for a class with Bloodlust. (This would be true even if the group hadn't filled the tank role yet.)

<img width="402" alt="image" src="https://user-images.githubusercontent.com/44137029/232312181-7d8fce3f-0f0d-4826-a64a-9ded5c028696.png">

What do you think about adding an option/keyword to only include groups where joining wouldn't stop the group from having Bloodlust? I would suggest "lustfit", "blfit" and "herofit", in analogy to partyfit. I think the semantics would be, "lustfit" is true if:

* Somebody in the group has lust, or
* somebody in my party has lust, or
* after joining, there is still an open dps or healer slot.

**Comment by 0xbs** [comment]
Good idea, will add that. Currently quite busy, so expect no fast implementation.

**Comment by 0xbs** [comment]
I implemented `blfit` and `brfit` in 3.8.1-beta
