### ISSUE TITLE
For dungeon search, surface partyfit in options

### ISSUE THREAD

**Issue by redcatelf** [0xbs/premade-groups-filter#169]
As an m+ player, I find that "partyfit" is by far the most useful filter option in this addon. Right now it's only discoverable if you read the whole keyword list and aren't being put off by making your own advanced expression query.

I wonder if it might make sense to surface partyfit in the options, at least when you're in the dungeon search pane? For dungeon search, partyfit seems like it mostly obviates the need for setting min/max on group members or tanks/dps/healers, so perhaps it makes sense to replace it like this:

<img width="397" alt="image" src="https://user-images.githubusercontent.com/44137029/232312853-9957d66c-3c18-4b23-ade9-dcf1d62dbc3d.png">

Again, this change would presumably only apply for dungeon search.

(If you end up implementing #168, adding the lustfit keyword as another option here might make sense as well, perhaps conditional only if your party doesn't already contain a bloodlust class, so as to not be confusing.)

**Comment by 0xbs** [comment]
There is now version [4.0.0-beta.1](https://github.com/0xbs/premade-groups-filter/releases/tag/4.0.0-beta.1) that shows a different filter window for each category. Please have a look and tell me what you think.

**Comment by 0xbs** [comment]
Now implemented!
