### ISSUE TITLE
Add sorting option, or make "appduration desc, mprating/pvprating desc" the default search order?

### ISSUE THREAD

**Issue by redcatelf** [0xbs/premade-groups-filter#170]
I only found out about the ability to sort by mprating by checking on the web. I'm finding it extremely useful, so I think it might be useful for many players to make this functionality more accessible.

I could imagine adding an dropdown "Sort by" option might be very useful, allowing for sorting by all the [rating options](https://github.com/0xbs/premade-groups-filter/wiki/Keywords#pvemythic). (I would posit that it should then sort by `appduration desc, [whatever you selected]`.)

Alternatively, it might even make sense to go without an option and just by default sort by "appduration desc, mprating desc" or "appduration desc, pvprating desc", depending on which search dialog you're in. I imagine this probably covers 90% of the use cases.

**Comment by 0xbs** [comment]
I thought about the same a lot and I think it is a good idea. The challenging part is to have the right default sorting and options in the dropdown for the different group types.

Premade Type | Default Sorting | Options in Dropdown | Comment
-------------|---------|---------------------|----------
Dungeons     | `mprating desc` | All `rio*`? What else? | However dungeons includes both M+ and Mythic. When a dungeon/expansion is new, players want m0 dungeons for gear. Sorting by rating does not make much sense in this case.
Raids        | ? | ? | Not sure. Very individual what your are looking for. Fresh groups? Groups with same ID as yourself?
Legacy Raids | ? | ? |
Quests       | ? | ? |
Custom       | ? | ? |
Arena        | `pvprating desc` | ? |
Skirmish     | ? | ? |
BG           | ? | ? |
RBG          | `pvprating desc` | ? | Maybe more?
Ashran       | ? | ? |
Custom       | ? | ? |

**Comment by redcatelf** [comment]
Judging by the listings, people don't really seem to be playing m0 much except during the very first week of the season. I imagine sorting by rating is still OK at that point, since it's all 0?

For what it's worth, during the first 2 weeks or so of each season, I find myself checking for last season's rio scores a lot. I don't think last season's rio is available through any of the variables right now. But if we had it available, it might be useful to use it as a tie breaker in the default sorting, for the case where the current ratings are all 0.

**Comment by 0xbs** [comment]
There is `rioprev` and more if you have Raider.IO installed: [Keywords Wiki Page](https://github.com/0xbs/premade-groups-filter/wiki/Keywords#raiderio)

**Comment by 0xbs** [comment]
I will implement default sorting by mprating descending. You may always overwrite the default sorting in the first weeks with your own search expression.
