### ISSUE TITLE
DF S2 - Slugs from Raider.io

### ISSUE THREAD

**Issue by creazy231** [0xbs/premade-groups-filter#172]
Would it be possible to match the slugs raider.io is using?

![image](https://github.com/0xbs/premade-groups-filter/assets/13473174/8f705670-498e-4c56-ae88-fd2e0fa69d20)

**Comment by maphex** [comment]
https://github.com/0xbs/premade-groups-filter/pull/173
I suggested the update via a pull request

**Comment by 0xbs** [comment]
Fixed in version 3.8.2
