### ISSUE TITLE
'blfit' keyword gives this error

### ISSUE THREAD

**Issue by SeanSawyers** [0xbs/premade-groups-filter#176]
![image](https://github.com/0xbs/premade-groups-filter/assets/61792546/c81238d3-c0a1-4b75-a849-38eead528d92)

Edit: For clarity, this is the custom filter I'm currently using:
![image](https://github.com/0xbs/premade-groups-filter/assets/61792546/c9c6a29f-d53e-420a-932e-cc269639b1ef)
When "and blfit" is removed the error disappears

Edit 2: Now I'm not sure that's what's causing it.

Using this does not give the semantic error:
![image](https://github.com/0xbs/premade-groups-filter/assets/61792546/91f42d4b-f6c6-415f-9f34-98442e30e038)

But this one does:
![image](https://github.com/0xbs/premade-groups-filter/assets/61792546/bc27a01f-e31b-4477-b9d6-01ae1aa71f33)

I guess it's the 'uld' part?
![image](https://github.com/0xbs/premade-groups-filter/assets/61792546/4fe726a6-b877-45dc-af7c-38f619b2de76)

![image](https://github.com/0xbs/premade-groups-filter/assets/61792546/8e00026d-31a2-4f37-8281-f4ac24f602d4)

'nelt' also gives this error:
![image](https://github.com/0xbs/premade-groups-filter/assets/61792546/17698571-c6af-4e2a-afef-65504075dcc0)

**Comment by 0xbs** [comment]
New keywords `blfit` and `brfit` only work in the latest beta version of the addon. Do have the beta installed?

PGF uses different keywords than Raider.io. I can add aliases.

Here are the [PGF season 2 keywords](https://github.com/0xbs/premade-groups-filter/wiki/Keywords#dragonflight-season-2-mythic)

**Comment by SeanSawyers** [comment]
> New keywords `blfit` and `brfit` only work in the latest beta version of the addon. Do have the beta installed?
> 
> PGF uses different keywords than Raider.io. I can add aliases.
> 
> Here are the [PGF season 2 keywords](https://github.com/0xbs/premade-groups-filter/wiki/Keywords#dragonflight-season-2-mythic)

Ah gotcha. I don't have the beta installed, I just saw 'blfit' on the keywords list and didn't know it was only in beta. Adding the aliases would be much appreciated.
Thanks!
