### ISSUE TITLE
(BUG) keyword blfit causes semantic error message

### ISSUE THREAD

**Issue by thowsen** [0xbs/premade-groups-filter#177]
As a non-bl character; typing ```blfit```  causes a semantic error "nil of type nil".  However, ```hasbl``` works.

I think either ```PGF.PlayerOrGroupHasBloodlust()``` or ```PGF.HasRemainingSlotsForBloodlustAfterJoin(memberCounts)``` returns nil.
https://github.com/0xbs/premade-groups-filter/blob/401118d19274270dff72bba549d8671077a2822c/Main.lua#L393

**Comment by 0xbs** [comment]
I tested with a warrior and both blfit and brfit are working fine. So I think there is another problem.

**Comment by 0xbs** [comment]
Closed due to inactivity.
