### ISSUE TITLE
Raider IO API change breaks rio and riomain functionality

### ISSUE THREAD

**Issue by darthginger** [0xbs/premade-groups-filter#18]
from the raider io discord:
- LUA API changes: profile.allScore and profile.mainScore are deprecated and only return 0 now. To access the actual score, access the values profile.mplusCurrent.score, profile.mplusPrevious.score, profile.mplusMainCurrent.score, or profile.mplusMainPrevious.score. Role scores are also no longer in the addon, but each of those subtables has a role table that indicated the order of each role (0 = off, 1 = 1st, 2 = 2nd, 3 = 3rd)

**Comment by 0xbs** [comment]
Fixed in 1.26
