### ISSUE TITLE
Can't create group without authenticator

### ISSUE THREAD

**Issue by Enkaf** [0xbs/premade-groups-filter#180]
Hello!

Since I dont have full protection account, I can't list my group when addon (PGF) is enabled, with default name. Scr:

![image](https://github.com/0xbs/premade-groups-filter/assets/28902145/a29d3333-3e50-4478-ad43-2eb534be5ad9)

When addon (PGF) is disabled I can list my group with default name.

![image](https://github.com/0xbs/premade-groups-filter/assets/28902145/11fd8f20-3082-4b4d-bdf1-c2ce061f16d5)
![image](https://github.com/0xbs/premade-groups-filter/assets/28902145/8802b5d7-4598-487c-a098-0ccfad15b5d3)

I know, I can't rename/name premade grp, but default name is available. 

I use last version addon it's 4.0.0 (Jun 13, 2023)

thanks.

**Comment by 0xbs** [comment]
Thanks for the report, will investigate.

**Comment by 0xbs** [comment]
Do you see the following message after login?
> Premade Groups Filter: Will not apply fix for 'Interface action failed ...

Could you please run the two commands (one after another) and post the results here?
```
/dump C_LFGList.IsPlayerAuthenticatedForLFG(1160)
/dump C_LFGList.IsPlayerAuthenticatedForLFG(1164)
```

**Comment by Enkaf** [comment]
well, I found issue. I was disable a print message in lua file code, sorry :)

![image](https://github.com/0xbs/premade-groups-filter/assets/28902145/39de54f0-c8c5-4152-b8fe-4d54b7eed977)

Just want to make more clean chat...

**Comment by 0xbs** [comment]
Perfect!
