### ISSUE TITLE
Comments in advanced expression

### ISSUE THREAD

**Issue by BradCOnGitHub** [0xbs/premade-groups-filter#184]
Before the recent overhaul I was able to keep a commented out filter as the only text in the advanced expression field, to be uncommented when I needed it. Now I get a parsing error when the comment is the only thing there.

Specifically, I put this: 
`
--mages > 0`
I have been able to work around it with this:
```
true 
--and mages > 0
```

**Comment by 0xbs** [comment]
Fixed in 4.0.3
