### ISSUE TITLE
Sort groups by time 

### ISSUE THREAD

**Issue by zeenk** [0xbs/premade-groups-filter#185]
Previously with the 3.8.3 release I could use another [addon](https://www.curseforge.com/wow/addons/premade-sort) to have it sort the newest groups at the top but with the new ui update it seems to have broken that so it no longer works, could you possibly look into that so the two addons can work together again? :)

3.8.3:
![2023-06-14_20-12-41](https://github.com/0xbs/premade-groups-filter/assets/68170439/6594d304-9b31-4f9c-9970-8e8d9db9556d)
4.0.2:
![2023-06-14_20-10-48](https://github.com/0xbs/premade-groups-filter/assets/68170439/1d00f99c-2b3e-4380-9d30-3e435ac40a38)

**Comment by 0xbs** [comment]
I assume live filtering broke the interaction. PGF support filtering, but only in expert mode (click minimize button in title bar) by entering e.g. `age desc` in the sorting box.

Most players seem to be happy with sorting by M+ rating. I already thought about adding a dropdown for predefined sorting options, but I am not sure if more than a few players are interested in different sorting options.

**Comment by zeenk** [comment]
Ah I see, yeah ``agesecs asc`` works but it removes the other selected filters I have from normal mode but a dropdown to choose between time or score sorting would be sweet for the normal mode 👍

**Comment by zeenk** [comment]
One more thing I noticed with expert mode on, the signed up groups can't be shown at the top anymore only works when you are in normal mode 😔 
![2023-06-15_21-22-30](https://github.com/0xbs/premade-groups-filter/assets/68170439/bd27f8ce-1345-43b1-b1e5-8d1ec5e9abad)
![2023-06-15_21-23-03](https://github.com/0xbs/premade-groups-filter/assets/68170439/95a753b3-7643-41d7-b772-edb59d3de2b2)

**Comment by zeenk** [comment]
Nice, I did ``appduration desc, agesecs asc`` as sorting option instead and now it works they way I wanted it so closing this issue. thx for the help 😄
