### ISSUE TITLE
[Request] Auto Note

### ISSUE THREAD

**Issue by totalschaden** [0xbs/premade-groups-filter#19]
Would be awsome if there was an option to auto. fill the note to the Group Leader when Queuing for a Group when Choosing Role.

**Comment by 0xbs** [comment]
Sound like a great idea (although I am not sure what you’d like to fill into the note), but honestly I think it is a bit out of scope for a group filtering addon. But why don’t you just write your own addon that does exactly that? It’s not as difficult as it sounds and I think the idea is worth a separate addon.

**Comment by totalschaden** [comment]
I think it would fit as it has to do with finding a group too. I always get asked if I have a BL or Tranq/Dispel Pet when queueing for higher m+ groups, would be realy handy if I can put it into the note automaticly.

I have not looked into Developing Addons for WoW yet, not sure if its worth getting into it just for a little feature like this :) Would be nice if you consider adding it or make a seperate one.

**Comment by 0xbs** [comment]
I had a second look into this issue. It seems that it is impossible to modify the content of the application text box with an addon. Bizzard even [disabled setting and pasting text](https://github.com/tomrus88/BlizzardInterfaceCode/blob/1ee90881c45114dce6ca869486666282f03b6b35/Interface/FrameXML/LFGList.xml#L1948).
