### ISSUE TITLE
Ratings Boxes Slightly Too Small

### ISSUE THREAD

**Issue by Jdaddy0007** [0xbs/premade-groups-filter#190]
First I love this addon, and really love the changes you are making!!!

See below:
![Wow_xPN9JDtTeB](https://github.com/0xbs/premade-groups-filter/assets/73510236/9b5db1ae-d40a-40e1-8213-0d6a8a32db8c)
Apparently my friends using Ultra wide monitors don't have this issue... but the ratings boxes can only see 3 characters... on the 4th entry everything on the left is cut off.

Should note that it's always been like this for me, this isn't a recent issue.

**Comment by 0xbs** [comment]
I already increased the size in one of the last updates, but it seems it's not enough.

It looks like you increased the font size but not necessarily the UI scaling. Where did you increase it and to what value?
