### ISSUE TITLE
Filter for main mprating

### ISSUE THREAD

**Issue by Iconqt** [0xbs/premade-groups-filter#200]
Request:

- allow a filter for mprating on someones main (something like mpratingMain)

Thanks for the awesome addon!

**Comment by 0xbs** [comment]
Blizz does not provide the information, but if you have Raider.io installed, you can use the `riomain` keyword and many more. See [keywords wiki page](https://github.com/0xbs/premade-groups-filter/wiki/Keywords#raiderio).

Example:
```
( mprating >= 1000 or riomain >= 1200 )
```

**Comment by Iconqt** [comment]
Oh thats great, did not know that this keyword was already included. Thanks so much :)
