### ISSUE TITLE
Add option to show current PB in group hover tooltip

### ISSUE THREAD

**Issue by xAt0mZ** [0xbs/premade-groups-filter#202]
**Suggestion**
Add an option to show the current PB for the dungeon in the hover tooltip, depending on the current main affix (Tyrannical / Fortified)

**Why**
Avoids to back & forth between the Party Finder and the M+ tab to know for each DJ what is the max key done

**How**
A simple `Personal Best : +X` with the value we usually find in the M+ tab would be enough

![image](https://github.com/0xbs/premade-groups-filter/assets/7642331/d50c78f7-baa4-47bd-bfeb-47b2e1d65abc)
![image](https://github.com/0xbs/premade-groups-filter/assets/7642331/74ac7494-f910-40bf-86da-be335c0ff64d)

Thanks for this awesome addon!
❤️

**Comment by 0xbs** [comment]
I see the need for that, but it also doesn't really fit into the scope of this addon.

May I suggest the [Weak Aura _Mythic+ Key Levels_](https://wago.io/zYp2nc82S/) which shows you the same information right underneath the group listing? I am using it myself and do like it very much.
