### ISSUE TITLE
idea: show # results returned from api and # shown after filtering by expression

### ISSUE THREAD

**Issue by belatar** [0xbs/premade-groups-filter#204]
hi, pgf is a dream for queueing and i would like to suggest a feature.

iirc the api returns a maximum of 100 results filtered only by the search box (keylvl and dungeon name). if more than 100 match serverside, then random 100 are returned. the client then additionally filters those results down.
to better adjust queries i would like to see the number of results returned from the api and the filtered down number that is actually shown.
something like: "showing 8/85 results"
if the number of the api results is >100 this would be an indicator to further narrow in the searchbox to reduce the randomness.
i could first probe whether there are more than 100 22-23 keys on offer and then filter further down.

thanks for reading, cheers, bela

**Comment by 0xbs** [comment]
When you hover over the PGF checkbox (the one above the group listing) with your cursor, you should see a tooltip that shows exactly what you want. It's a bit hidden, but I did not find a better place so far and I assume most players don't care or don't draw the same conclusions you do.

**Comment by Belatar** [comment]
awesome, thanks. as to where to display the info: maybe show it at the top of advanced expressions, if the user chooses to use them. pretty sure only users who can handle and interpret the info will choose advanced mode. its fine the way it is, would just save the hover.

**Comment by 0xbs** [comment]
Closing for now as I do not plan to add an option at the moment.
