### ISSUE TITLE
Feature to search for keys that would be an upgrade for me or someone in my group

### ISSUE THREAD

**Issue by Frossy** [0xbs/premade-groups-filter#208]
Hey,
first of all i want to thank you for creating this addon. I use it all the time and it is a huge quality of life enhancement.

I am a software engineer myself and was thinking about contributing to the project. I have little to no experience with wow addons, so i wanted to ask if my idea is feasible before dumping a lot of time into it. 
I was thinking of adding a feature that would allow me to filter for keys that would be an upgrade for me or someone in my group according to our raider.io data. Do you think this would be doable, or am i missing something crucial here? 

Thanks in advance :)

**Comment by 0xbs** [comment]
Hi, thanks for reaching out!

To provide this feature, you need the key level of each group to calculate the possible upgrade. The only source for key level is the group title, which is protected and cannot be read by addons. Therefore not possible.

Also see #206, #147, #155, #136.

**Comment by Frossy** [comment]
Hey, thank you for the quick answer. I did not know that and also did not check the other issues. My bad.
