### ISSUE TITLE
I think the raid progress filter (rioheroicprogress specifically) isn't working correctly.

### ISSUE THREAD

**Issue by gotex007** [0xbs/premade-groups-filter#209]
If I sort by rioheroicprogress>8 (aotc only) then it filters out two of the three groups that do meet this criteria for some reason. I think rioheroicprogress might be looking at their main's progress because it's happening with no other filters (other than heroic) enabled and I can't figure out out why two eligible groups are filtered.

[My Search](https://i.imgur.com/D8QQy0Z.png)
[The found eligible group](https://i.imgur.com/FMdoswU.png)
[The first group not found](https://i.imgur.com/I7aDh9K.png) and [The second group not found](https://i.imgur.com/FAdsgHF.png)

**Comment by 0xbs** [comment]
Your queries are correct and the two groups should appear in the search. 

I suspect that there is indeed a bug in the calculation logic if the raid leader has progress in multiple raids and the last one in the list is not the desired raid. The code loops over all progress entries and the last one "wins".

I will check if that is really the case. If yes, I wonder how to fix it. I could use the first entry instead. Or I could calculate the maximum. Or I can try to associate Rio's abbreviations with the current activity but that requires an update on each new raid :/
