### ISSUE TITLE
PGF Changes rclick "report advertisement" function

### ISSUE THREAD

**Issue by Bibbley** [0xbs/premade-groups-filter#214]
Having PGF installed makes it so that rclicking a group posting and selecting report advertisement opens the select report reason window instead of instantly reporting the post for advertising

**Comment by 0xbs** [comment]
See 2nd FAQ entry: https://github.com/0xbs/premade-groups-filter/wiki/FAQ#report-advertisement-shows-the-report-dialog-instead-of-directly-reporting-the-group
