### ISSUE TITLE
FR: dispells available filter

### ISSUE THREAD

**Issue by SvenvnevS** [0xbs/premade-groups-filter#218]
please add something to filter available dispells for the afflicted affix week. as it really helps finding groups when u cannot dispell the affix yourself

            env.dispells = env.shamans + env.evokers +  env.priests + env.mages + env.paladins + env.monks + env.druids

could be a solution in the main.lua in between line 343 and 347 (works for me)

variable should probs have a better name tho..

**Comment by 0xbs** [comment]
Now live in version 5.1.0. Thanks for the PR.
