### ISSUE TITLE
Add ! negation filter in main filter. ie !icecrown to remove all the icecrown raids

### ISSUE THREAD

**Issue by jeffbee75** [0xbs/premade-groups-filter#219]
We can easily search for a specific raid, but would be nice to filter out all of a specific raid(or multiples !icecrown and !togc as opposed to just listing a raid you search for

Thx!

**Comment by 0xbs** [comment]
You can now use the [wrath raid keywords on the wiki page](https://github.com/0xbs/premade-groups-filter/wiki/Keywords#wrath) in version 5.1.0. Examples: 
* `not icc`
* `( toc or rs )`
* `not icc and not rs`

**Comment by jeffbee75** [comment]
you da bomb dude! ;)

<http://www.avg.com/email-signature?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Virus-free.www.avg.com
<http://www.avg.com/email-signature?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>
