### ISSUE TITLE
appduration sort not working

### ISSUE THREAD

**Issue by hollo6** [0xbs/premade-groups-filter#221]
### Game Version
Retail

### Lua error from Bugsack
There is no LUA error.

### Screenshots
![image](https://github.com/0xbs/premade-groups-filter/assets/365584/e9c9e85c-b09f-422f-b9ab-de5d22721cc7)

### Current behaviour
Appduration sort has no effect.

### Steps to reproduce
1. Open premade dungeon list
2. Set up any filter
3. Set sort to: appduration desc, mprating desc, agesecs asc

### Expected behaviour
Applied groups should be sorted to the top because that's the first in the sort list.
This was working before 10.2.

**Comment by 0xbs** [comment]
I can confirm the bug. It occurs as soon as more than one sorting expression is entered.
