### ISSUE TITLE
Lua Error on hovering over players in applicant list

### ISSUE THREAD

**Issue by mdk12** [0xbs/premade-groups-filter#223]
Please check FAQ and existing issue first:
- FAQ / Wiki: https://github.com/0xbs/premade-groups-filter/wiki/FAQ
- All Issues: https://github.com/0xbs/premade-groups-filter/issues?q=

### Game Version
Retail

### Lua error from Bugsack
```
471x FrameXML/LFGList.lua:1877: bad argument #1 to 'format' (string expected, got nil)
[string "=[C]"]: in function `format'
[string "@FrameXML/LFGList.lua"]:1877: in function `LFGListApplicantMember_OnEnter'
[string "*LFGList.xml:198_OnEnter"]:1: in function <[string "*LFGList.xml:198_OnEnter"]:1>

Locals:
(*temporary) = "%s %s"
(*temporary) = nil
(*temporary) = "Warrior"
(*temporary) = "string expected, got nil"
```

### Screenshots
Screenshots which show your filters and where the issue happened are extremely helpful.
Drag your screenshot files here (do not paste). Full un-cropped screenshots are preferred.

### Current behaviour
Describe what your issue here as detailed as possible.

When checking applicants for a dungeon and hovering over them I sometimes get spammed by the above mentioned lua error and the tooltip for raider.io doesn't show. Weirdly it is only every 20 player where it happens and so far I would say it happens for all classes.

### Steps to reproduce
1. Open premade dungeon list
2. Setup filters ...
3. Click on ...

### Expected behaviour
Describe what you expect to happen.

To be able to hover over players and ElvUI and Raiderio Tooltips to load.

**Comment by 0xbs** [comment]
This is actually a Blizzard bug introduced in 10.2 and also happens when PGF is not installed. It happens when you hover over a group of two or more applicants.

See https://github.com/Stanzilla/WoWUIBugs/issues/502

**Comment by StFreve** [comment]
Created WeakAura with temporary fix if anyone wants: [Fix Error LFGList.lua:1877](https://wago.io/W_RuyS0n6). It makes `GetSpecNameBySpecID` to return empty string instead of `nil` when no real specID is passed.
