### ISSUE TITLE
Error when pressing Hearthstone after M+ Dungeon

### ISSUE THREAD

**Issue by CasiQT** [0xbs/premade-groups-filter#228]
After finishing M+ Dungeons Ill often (not always) get this error when pressing the Hearthstone to leave the dungeon. 
After a "/reload" it works fine. 

Bugsack Error: 
1x [ADDON_ACTION_FORBIDDEN] AddOn 'PremadeGroupsFilter' tried to call the protected function 'UNKNOWN()'.

**Comment by 0xbs** [comment]
Even though PGF is blamed in the error message, I assume that the actual cause is something else, maybe another addon like some keystone helper or WeakAura. Hard to tell as even the protected function is literally unknown.
