### ISSUE TITLE
Breaks "start group" autofill for key level

### ISSUE THREAD

**Issue by kodebytes** [0xbs/premade-groups-filter#229]
Please check FAQ and existing issue first:
- FAQ / Wiki: https://github.com/0xbs/premade-groups-filter/wiki/FAQ
- All Issues: https://github.com/0xbs/premade-groups-filter/issues?q=

### Game Version
Retail 

### Lua error from Bugsack
```
Not error related
```
### Current behaviour
When using the addon, your current key level is not auto filled into the input box when starting a group. This is a default wow behavior. With the addon disabled, the auto fill of the key level works fine.

### Steps to reproduce
1. Open Premade Groups
2. Click Dungeon
3. Click Start Group
4. the "description" field is blank when it should auto fill "+21" for example

### Expected behaviour
When creating groups normally, the default wow UI will auto fill your current key level into the description

**Comment by 0xbs** [comment]
Have you read the very first FAQ entry?
