### ISSUE TITLE
Add Keyword for Augmentation Spec

### ISSUE THREAD

**Issue by lholbert** [0xbs/premade-groups-filter#232]
Please check FAQ and existing issue first:
- FAQ / Wiki: https://github.com/0xbs/premade-groups-filter/wiki/FAQ
- All Issues: https://github.com/0xbs/premade-groups-filter/issues?q=

### Is your feature request related to a problem? Please describe.
Lust has its own keyword, would be nice to have Augmentation (or perhaps "support" in case new specs are added)

### Describe the solution you'd like
Augmentation keyword for advanced filter expression

### Describe alternatives you've considered
Manual observation which feels weak considering the nature of this addon.

**Comment by 0xbs** [comment]
See #222. I would need a list of all localized spec names there are in the game as used in the group finder tool.

**Comment by 0xbs** [comment]
Now possible in version 5.3.0 by using e.g. `augs == 0`
