### ISSUE TITLE
Report Adverstisement Behavior

### ISSUE THREAD

**Issue by Sebaision** [0xbs/premade-groups-filter#233]
### Game Version
Retail 

### Lua error from Bugsack
 N/A

### Screenshots
![WoWScrnShot_012624_104704](https://github.com/0xbs/premade-groups-filter/assets/157818132/b51a3c7d-579b-4409-8081-1f4a8b08f152)
![WoWScrnShot_012624_104728](https://github.com/0xbs/premade-groups-filter/assets/157818132/5bee498d-417c-4200-8f68-02bda2d11b3a)

### Current behaviour
I noticed that without the PGF addon, if I report someting as adverstisement, it immedietly reports and hides the group, without any further action needed. However, with the PGF addon enabled, clicking the report advertisement option brings up the old blizz style report UI, where you would need to manually enter details.
Note that simply unchecking the PGF checkbox in the groupfinder does not alter this behaviour either. 

### Steps to reproduce
1. Open premade dungeon list
2. Find advertisement
3. Right click and select report advertisement (with and without PGF enable)

### Expected behaviour
I would assume based on the factors above, PGF is reducing the ability for the blizzard UI to report advertisements with ease. 
Expected behaviour would be no difference in reporting ease and ability I suppose.

**Comment by 0xbs** [comment]
See second FAQ entry.
