### ISSUE TITLE
Add ranges for the various M+ crest difficult

### ISSUE THREAD

**Issue by 4ndrewCox** [0xbs/premade-groups-filter#234]
Please check FAQ and existing issue first:
- FAQ / Wiki: https://github.com/0xbs/premade-groups-filter/wiki/FAQ
- All Issues: https://github.com/0xbs/premade-groups-filter/issues?q=

### Describe the solution you'd like
The addon is able to filter M+ keys by a range of values based on the name of the crest.
For example, if looking for "dreaming" crests, it would filter for key levels 6-10, etc.

### Describe alternatives you've considered
Searching for the crest range manually does work, such as 6-10, but its tedious.

**Comment by 0xbs** [comment]
Not possible. Addons cannot read the group title, which is the only source for the key level. See all the other requests for "only keys that upgrade my rating" or similar.
