### ISSUE TITLE
Automated application

### ISSUE THREAD

**Issue by Mindaugas05** [0xbs/premade-groups-filter#235]
### Is your feature request related to a problem? Please describe.
Playing at high end of m+ and not a meta class leads to a lot applications, time in doing so and manual labor. 

### Describe the solution you'd like
Would like to automatize application to keys based on dungeon and selected level.

### Describe alternatives you've considered
There are none

### Additional context
No clue if its even possible to do, I have a background in frontend dev, but no experience in wow addon dev. Would like to help out in any capacity i can if you would consider implementing it.

**Comment by teelolws** [comment]
Cannot be done completely automatically as C_LFGList.ApplyToGroup requires a hardware event: https://warcraft.wiki.gg/wiki/API_C_LFGList.ApplyToGroup

Might be able to turn it into a one button apply thing but at that point... why bother imo

**Comment by 0xbs** [comment]
@teelolws is correct, same for cancellation. And you may only have five pending applications anyway. Try to apply smart by choosing groups that need your spec.
