### ISSUE TITLE
5.3.0 Guardian spec info is wrong

### ISSUE THREAD

**Issue by hollo6** [0xbs/premade-groups-filter#238]
### Game Version
Retail

### Lua error from Bugsack
There is no error.

### Screenshots
N/A

### Current behaviour
Not sure exactly how big of a problem this causes during actual usage but Guardian is listed as ranged:
    [ 104] = { class = "DRUID",       spec = "GUARDIAN",      range = true,  melee = false },

All the other specs seem fine.

**Comment by 0xbs** [comment]
Thanks for the report!
