### ISSUE TITLE
[Request] Add support for Rio raid progress

### ISSUE THREAD

**Issue by eyriewow** [0xbs/premade-groups-filter#24]
The rio keyword is really useful for filtering mythic+ groups.

I would like to see something similar to filter out raid group listings with leaders that don't meet certain progression thresholds to avoid 6/8N group leaders that advertise hc zerg groups.

**Comment by 0xbs** [comment]
Next version supports `rionormalprogress`, `rioheroicprogress`, `riomythicprogress`, `riomainprogress`, `rionormalkills`, `rioheroickills`, `riomythickills` and `rioraidbosscount`. Have a look at the [list of keywords](https://github.com/0xbs/premade-groups-filter/wiki/Keywords)!
