### ISSUE TITLE
Appduration sorting expression does not work

### ISSUE THREAD

**Issue by DimitrisLK** [0xbs/premade-groups-filter#240]
### Game Version
Retail

### Lua error from Bugsack
No errors

### Screenshots
![Wow_IF95MNdG67](https://github.com/0xbs/premade-groups-filter/assets/32920285/a686e717-edce-43a9-975b-3d2555227987)

### Current behaviour
the `appduration` filter does not currently work and the currently queued groups are only sorted at the bottom of the LFG window. 

### Steps to reproduce
1. Open premade dungeon list
2. Setup the `appduration` sorting filter on either ascending on descending.
3. Click `Search`

### Expected behaviour
It should filter the currently queued groups to the top or bottom, depending on the asc/desc order.

**Comment by 0xbs** [comment]
Does it only sometimes not work or always?

Blizzard fetches search results and application from two different APIs:

1. `C_LFGList.GetFilteredSearchResults()` - returns search results and applications, PGF filters and sorts these results
2. `C_LFGList.GetApplications()` - most of the time empty, sometimes contains applications from other categories

I have not yet found out the difference between those two. Whenever your application are returned by the second API, I cannot filter them and they are always displayed at the bottom, even without having PGF installed.

**Comment by DimitrisLK** [comment]
Always, whether I close the addon via checkmark or the addon panel alltogether. 

I assume there's no way to specify the API to use to return the correct results, right?

**Comment by 0xbs** [comment]
No or I don't know how. It would be theoretically possible for me to mix these two lists somehow, but it does not look easy.

**Comment by DimitrisLK** [comment]
Found the potential culprit, I disabled this option in ElvUI Windtools and it seems to have fixed the issue for now. 
![image](https://github.com/0xbs/premade-groups-filter/assets/32920285/d1936ece-ec69-4901-bdd6-e54865a95df0)

**Comment by 0xbs** [comment]
Great you found the problem! There was a Blizz bug where the two mentioned APIs provided duplicate data, but Blizz fixed that some time ago.
