### ISSUE TITLE
Option to ignore specific groups

### ISSUE THREAD

**Issue by hollo6** [0xbs/premade-groups-filter#241]
Please check FAQ and existing issue first:
Done, can't find any solution or workaround.

### Is your feature request related to a problem? Please describe.
Without being able to filter for group name, the result list is always overloaded with uninteresting groups (e.g. looking for multiple key levels for multiple dungeons but only a subset of their combinations is relevant) or undesired ones (bait tags in description or trolls who keep their groups listed but never invite anyone). This often makes finding the right groups to apply to very hard - and slow, which can result in missing a spot by applying too late.

### Describe the solution you'd like
A perfect solution for this would be an "ignore group" in the right-click menu and a keyword to filter them.

### Describe alternatives you've considered
Only thing that could be a half-solution for this is the ability to filter for group names but IIRC that is not possible for addons anymore.

### Additional context
I'm pretty sure this is doable based on the group ID. I know that it sometimes changes and these groups would pop up again and that's okay, this would still be a huge improvement.

**Comment by 0xbs** [comment]
Closed in favour of duplicate issue #153
