### ISSUE TITLE
Question à propos d'un filtre pour les clés Mythiques +

### ISSUE THREAD

**Issue by Machou** [0xbs/premade-groups-filter#243]
Bonjour,

Je ne savais pas trop où demander et je n'ai pas trouvé de réponse dans la FAQ.

Est-ce possible de filtrer les clés Mythiques + uniquement en +20 si je souhaite une +20, et non une +19 / + 20 / + 21 ?

Cordalement

**Comment by 0xbs** [comment]
Pas avec PGF, mais il est possible d'entrer dans le champ de recherche au-dessus de la liste des groupes « 20-20 » pour seulement +20 ou même « atal 20-20 ». Se trouve également dans la FAQ comme premier point 😉

**Comment by Machou** [comment]
> Pas avec PGF, mais il est possible d'entrer dans le champ de recherche au-dessus de la liste des groupes « 20-20 » pour seulement +20 ou même « atal 20-20 ». Se trouve également dans la FAQ comme premier point 😉

J'ai eu beau chercher, mais je n'ai pas trouvé ^_^

En tout cas super ! merci beaucoup :)
