### ISSUE TITLE
Remember role selection so you don't have to accept pop-up each time you try to join a group

### ISSUE THREAD

**Issue by moisalucian** [0xbs/premade-groups-filter#244]
Add a role selection that will be remembered all the time, so you don't have to select it each time in popup

### Describe the solution you'd like
[It's already implemented on this addon - premade-group-finder](https://www.curseforge.com/wow/addons/premade-group-finder)

Option in the down area -> Sign up as:    Tank/Heal/DPS

**Comment by 0xbs** [comment]
The role selection is already remembered automatically. If you still see role popups, make sure you have option "One Click Signup" enabled. Also check if other addons are interfering.

**Comment by moisalucian** [comment]
![image](https://github.com/0xbs/premade-groups-filter/assets/58365758/4d70c18e-cd7e-4fdc-ad2f-7004b8d94ed6)

Hmm, not sure If i can find One Click Signup ( check picture). Actually, now that I read readme, I can't find anything from the options mentioned under "Additional UI Enhancements". Can you please explain where are those things pls? Eventually include them in readme.

Additional mark, would be amazing if you can include specs as icons, so when you searching for a dungeon, you can insta have an overview over multiple dungeons, not having to hover mouse over each one.
Example from other addon (premade-group-finder) which already have implented that, in case you can get inspiration from. Also the format of the text seems a bit more clear an concise there.

https://www.curseforge.com/wow/addons/premade-group-finder

The thing that this addon is missing is exactly all the great filters that you actually did on this repo, thanks for that. A combination of this two (ui from them and filters from you would be amazing).

Thanks for answering!

**Comment by 0xbs** [comment]
It's not in the filter window, but in the options. Press ESC → Options → Select "Addons" tab → Select "Premade Groups Filter" in the list and you will see checkboxes on the right. If you hover over them with the mouse, you get a detailed help text.

Spec icons are already on my list of things to do. I most likely won't enable them by default as I find them hard to distinguish and the spec only matters for a few DPS specs.
