### ISSUE TITLE
Feature Request: Filter groups to ones resulting in rating gain

### ISSUE THREAD

**Issue by TheSavior** [0xbs/premade-groups-filter#245]
### Game Version
Retail 

### Feature Request
I'm curious how feasible it would be to add an advanced filter for groups that would result in a rating gain for my character, if they are timed.

I was looking at the source code for the [Rating Gain addon](https://www.curseforge.com/wow/addons/mythic-plus-rating-gain): https://gist.github.com/TheSavior/b7f244ac7d5be32447f7a6d318f0852a#file-mythicplusratinggain-lua-L78-L124 and the calculations and functions used seem pretty straight forward. 

I assume the most challenging piece would be knowing the level of the key, which would have to be inferred from the group name, which probably kinda sucks. Is that is reasonable to do? Are there any other things already in Premade Groups Filter that does something kinda like this? Would the perf be prohibitive?

**Comment by 0xbs** [comment]
Asked many times already, but not possible to get the key from the group name.

See #208, #206, #147, #155, #136.

**Comment by TheSavior** [comment]
Oh interesting, I definitely had tried to search for this over the last couple weeks while I've been thinking about this. I wonder why SEO for this is so bad that it's caused so many people to ask. 

Oh well, thanks for the info. Is this the weak aura you are using (from one of your linked issues): https://wago.io/zYp2nc82S

**Comment by 0xbs** [comment]
Yes that's the one.

I'll write an FAQ entry for the question, maybe that will help find it better in the future. It's really a shame that Blizz protected the group name and does not provide the key level in any other way. I blame Word Quest Group Finder a bit for that, that addon caused so much traffic that Blizz decided to lock everything down back in BfA.
