### ISSUE TITLE
When the "Blood Lust" option is enabled, groups are still searched without it

### ISSUE THREAD

**Issue by Hollicsh** [0xbs/premade-groups-filter#246]
When I search for groups with the "Blood Lust" option enabled, they are still found without it.

![Screenshot_2](https://github.com/0xbs/premade-groups-filter/assets/54585769/a8d00c37-121f-43de-89c6-52ca8419b076)

**Comment by 0xbs** [comment]
Are you playing a class that has bloodlust? Because `blfit` does not remove groups that do not have BL but shows all groups where at least one player provides BL *after* you joined.

If you want to see only groups that already have BL prior to you joining them, use `hasbl`.

**Comment by Hollicsh** [comment]
"Are you playing a class that has bloodlust?"
- Nope. Demon Hunter.

"If you want to see only groups that already have BL prior to you joining them, use hasbl."
- Ok, thanks !
