### ISSUE TITLE
Wrath Raid missing Karazhan raid keyword

### ISSUE THREAD

**Issue by Ferdonax** [0xbs/premade-groups-filter#247]
The IDs are only for lower and upper Karazhan for Mythic+ Shadowlands and nothing for WotLK.

**Comment by 0xbs** [comment]
So far, no TBC raids have been added, just the Wrath ones. I assume very little groups play Kara nowadays on the Wrath realms, so isn't it easier to just type the name in the search box above the group list if you're looking for a Kara group?

**Comment by Ferdonax** [comment]
There were too many, and I was trying to use the "not Kara" search syntax to filter them out.

**Comment by 0xbs** [comment]
Is this still an issue for you? If yes, I can have a second look.
