### ISSUE TITLE
Half of the dungeon sellecting buttons are not working.

### ISSUE THREAD

**Issue by Deye-997** [0xbs/premade-groups-filter#248]
Selecting Ruby Life Pools, Nokhud Offensive, Azure Vault or Algeth'ar Academy inputs "True" instead of their actual keyword.
The other 4 are working fine.

https://imgur.com/a/bZnOUOz
![pgf](https://github.com/0xbs/premade-groups-filter/assets/64900928/f656be8f-909b-4687-8813-c536239fea47)

**Comment by karpana** [comment]
adding to this ...
seems to only be affecting RLP, NO, AV and AA. (the first four)
the last 4 seem to be filtering properly.

**Comment by karpana** [comment]
and writing the query (rlp or no or av or aa) does work.
just the selector buttons not properly creating the query string

**Comment by 0xbs** [comment]
Fixed in 5.4.0 which should be distributed shortly.

**Comment by karpana** [comment]
just came down for me...
works like a charm.  
Thank you.
