### ISSUE TITLE
seems to be selecting party fit on the backend or something

### ISSUE THREAD

**Issue by cruzanstx** [0xbs/premade-groups-filter#250]
Is this secretly selecting party fit? I used to be able to do the following but seems like it changed to only show my currently selected spec. 

I attempted to use "(tanks + heals == 1) or (dps <= 2)" as a hybrid (druid) but can only find groups for the spec I currently am.

**Comment by 0xbs** [comment]
No, the addon does not apply any hidden filters. What you see is what you get. Checkboxes and fields on the upper half are combined with the advanced expression field using logical `and`. Also PGF only filters the data returned from the server, it does not apply any server-side filters. Also, if you switch off PGF using the PGF checkbox on top of the list, all filtering and sorting is disabled, you will get the default search result.

Blizz might have changed the way they return results from the server, maybe as a preparation for patch 10.2.7 with the new filter options. They always sorted groups that fit your current spec to the top, but all other groups should still be visible at the bottom of the list.

**Comment by cruzanstx** [comment]
Yea i tested what you suggested. It sure does look like they changed something. Thanks for the quick response!
