### ISSUE TITLE
Cataclysm Classic 

### ISSUE THREAD

**Issue by Road-block** [0xbs/premade-groups-filter#251]
Please check FAQ and existing issue first:
- FAQ / Wiki: https://github.com/0xbs/premade-groups-filter/wiki/FAQ
- All Issues: https://github.com/0xbs/premade-groups-filter/issues?q=

### Game Version
Cataclysm Classic enUS, 54525

### Lua error from Bugsack
```
4x PremadeGroupsFilter/Modules/Activity_Cata.lua:192: attempt to index global 'C' (a nil value)
[string "@PremadeGroupsFilter/Modules/Activity_Cata.lua"]:192: in main chunk
```

### Screenshots
Screenshots which show your filters and where the issue happened are extremely helpful.
Drag your screenshot files here (do not paste). Full un-cropped screenshots are preferred.

### Current behaviour
Describe what your issue here as detailed as possible.

### Steps to reproduce
1. Open premade dungeon list
2. Setup filters ...
3. Click on ...

### Expected behaviour
Describe what you expect to happen.

**Comment by Road-block** [comment]
[locals.txt](https://github.com/0xbs/premade-groups-filter/files/15217967/locals.txt)

**Comment by Road-block** [comment]
The file is merely missing the header
```lua
local PGF = select(2, ...)
local L = PGF.L
local C = PGF.C
```

**Comment by 0xbs** [comment]
That happens if I push the new version too quickly without testing. Thanks for the report, problem is now fixed!
