### ISSUE TITLE
Retail 10.2.7.54604 - Blizz Stealth Added Class Color Circles & Other Changes

### ISSUE THREAD

**Issue by voidzone** [0xbs/premade-groups-filter#252]
Not sure if you're aware yet but it appears Blizz stealth added Class Colored Circles to the Dungeon Finder, and a bunch of other stuff.

https://github.com/Gethe/wow-ui-source/blob/live/Interface/AddOns/Blizzard_GroupFinder/Mainline/LFGList.lua#L3263

https://github.com/Gethe/wow-ui-source/commit/f5ad9406b458a80af8091c045c01e28b8dfb2eb4#diff-3b97a7c1cc8fef0fbb4f6df6772a1663b383717954ff6ff2a9f9bb56fa4a1172R3298

It's creating some minor layout conflicts with PGF, if that feature or the class bars are enabled in the addon, as their indexing appears to be different.  It's also duplicating the member list in the tooltip.

![image](https://github.com/0xbs/premade-groups-filter/assets/2574525/0e32a5d0-df48-4b1d-8afe-d31753114471)

**Comment by 0xbs** [comment]
I'm aware of the patch and it's changes, but could not really test on PTR as there are usually no groups. I am very busy irl at the moment, so give me some time, I will fix it.

**Comment by phaiz** [comment]
Another thing missing is the timer showing how long the group has been listed. I don't know if his was part of the plugin, but if it was it's gone.

**Comment by 0xbs** [comment]
A first preview is available in version 5.6.0-beta. Class bar, class circles and leader crown features are disabled for now.

**Comment by 0xbs** [comment]
Now fixed in version 5.6.0
