### ISSUE TITLE
Remove class color from group list

### ISSUE THREAD

**Issue by Machou** [0xbs/premade-groups-filter#258]
Bonjour,

Depuis le patch 10.2.7 (? ou 10.2.6), on voit une couleur affichée lorsqu'on recherche une clé mythique. Comme dans cet exemple :

![](https://i.ibb.co/986ySf0/Wo-WScrn-Shot-051424-152211.jpg)

Dans une version précédente, on pouvait afficher / masquer la couleur des classes, mais actuellement ce n'est pas possible.

Est-ce possible de rajouter cette possibilité ?

Merci

==================================================

Hi,

Since patch 10.2.7 (? or 10.2.6), a color is displayed when searching for a mythical key. As in this example :

In a previous version, it was possible to show/hide the color of classes, but this is currently not possible.

Is it possible to add this option?

Regards

**Comment by 0xbs** [comment]
Salut, avec patch 10.2.7, Blizzard a intégré la plupart des fonctionnalités de PGF, y compris la couleur des classes. Les couleurs que tu vois sont de Blizzard lui-même et il n'y a pas d'option pour les supprimer.

Il est possible d'écrire code pour les remplacer par les anciens, mais la plupart des joueurs les apprécient, alors je n'ai pas l'intention de les changer.

---

Hi, with patch 10.2.7, Blizzard integrated most of PGF's features into the game. The class colors you see are the ones from Blizzard itself and there is no option to hide them.

It's possible to write code to replace them with the old ones, but as most players like them, I don't intend to change anything.

**Comment by Machou** [comment]
> Salut, avec patch 10.2.7, Blizzard a intégré la plupart des fonctionnalités de PGF, y compris la couleur des classes. Les couleurs que tu vois sont de Blizzard lui-même et il n'y a pas d'option pour les supprimer.
> 
> Il est possible d'écrire code pour les remplacer par les anciens, mais la plupart des joueurs les apprécient, alors je n'ai pas l'intention de les changer.

Va falloir prendre l'habitude hehe.
