### ISSUE TITLE
Add Members in Tooltip for raids again

### ISSUE THREAD

**Issue by Toy00** [0xbs/premade-groups-filter#263]
The feature was implemented ingame for Dungeons so it was removed  from the addon, but now its missing for the raidfinder because there is still the old filter system.

**Comment by 0xbs** [comment]
Could you please elaborate a bit more on what your missing, ideally with a screenshot of where exactly you're missing the members? What version of the game are you playing: Retail, Retail Remix, Wrath, Cata?

If you're talking about the class listing in the tooltip, I did not fully remove the feature, I just disabled the spec listing for dungeons as Blizz is now showing this list:

Here is my (German) raid listing, showing the list of classes:

![Screenshot 2024-05-28 205403](https://github.com/0xbs/premade-groups-filter/assets/8686266/262b7fa5-e4bf-4be4-9b02-6a81ac5da10c)

**Comment by Toy00** [comment]
That was exactly what i meant, retail aswell.
But problem seemed to be on my side.
Cleared the WTF files and reinstalled the addon... now it works.
Apologies and thanks for the quick reply.
