### ISSUE TITLE
Lua error when opening Group Finder list

### ISSUE THREAD

**Issue by n0proxy** [0xbs/premade-groups-filter#264]
Please check FAQ and existing issue first:
- FAQ / Wiki: https://github.com/0xbs/premade-groups-filter/wiki/FAQ
- All Issues: https://github.com/0xbs/premade-groups-filter/issues?q=

### Game Version
Retail - noticed in Remix

### Lua error from Bugsack
```
21x [ADDON_ACTION_BLOCKED] AddOn 'PremadeGroupsFilter' tried to call the protected function 'GetPlaystyleString()'.
[string "@!BugGrabber/BugGrabber.lua"]:485: in function <!BugGrabber/BugGrabber.lua:485>
[string "=[C]"]: in function `GetPlaystyleString'
[string "@Blizzard_GroupFinder/Mainline/LFGList.lua"]:4048: in function <...aceBlizzard_GroupFinder/Mainline/LFGList.lua:4037>
[string "=[C]"]: in function `LFGListUtil_SetSearchEntryTooltip'
[string "@Blizzard_GroupFinder/Mainline/LFGList.lua"]:2881: in function <...aceBlizzard_GroupFinder/Mainline/LFGList.lua:2878>

Locals:
_ = Frame {
 RegisterEvent = <function> defined @!BugGrabber/BugGrabber.lua:491
 0 = <userdata>
 UnregisterEvent = <function> defined @!BugGrabber/BugGrabber.lua:491
 SetScript = <function> defined @!BugGrabber/BugGrabber.lua:491
}
event = "ADDON_ACTION_BLOCKED"
events = <table> {
 ADDON_ACTION_BLOCKED = <function> defined @!BugGrabber/BugGrabber.lua:557
 ADDON_ACTION_FORBIDDEN = <function> defined @!BugGrabber/BugGrabber.lua:557
 PLAYER_LOGIN = <function> defined @!BugGrabber/BugGrabber.lua:551
 LUA_WARNING = <function> defined @!BugGrabber/BugGrabber.lua:566
 ADDON_LOADED = <function> defined @!BugGrabber/BugGrabber.lua:511
}

```

### Current behaviour
Lua error pops up when opening the Group Finder page. Doesn't seem to be any other sign of problem.

### Steps to reproduce
1. Open premade dungeon list
2. Observe lua error occur instantly

### Expected behaviour
1. Open premade dungeon list
2. No lua error occurs

**Comment by 0xbs** [comment]
Do you see a message "Will not apply fix for 'Interface action failed because of an AddOn' ..." on login? 
If yes, please read the corresponding [FAQ entry](https://github.com/0xbs/premade-groups-filter/wiki/FAQ#message-will-not-apply-fix-for-interface-action-failed-because-of-an-addon--on-login).

**Comment by 0xbs** [comment]
Closing as no response.
