### ISSUE TITLE
Does not work for Cata raids

### ISSUE THREAD

**Issue by Ferdonax** [0xbs/premade-groups-filter#266]
### Game Version
Cata 

### Current behaviour
Cata raids filters do not work

bara | boolean | Cata | Baradin Hold
bwd | boolean | Cata | Blackwing Descent
bot | boolean | Cata | The Bastion of Twilight
tfw | boolean | Cata | Throne of the Four Winds

**Comment by 0xbs** [comment]
Issue should now be fixed
