### ISSUE TITLE
matchingid/bossesahead wrong when no lockout

### ISSUE THREAD

**Issue by mbattersby** [0xbs/premade-groups-filter#268]
### Game Version
Retail

### Current behaviour

bossesahead returns 0 (and by extension matchingid is true) when the group has defeated bosses but the player has no lockout. It should consider all the bosses defeated as being ahead and matchingid to be false.

Fix is to change the last fallback return of `PGF.GetLockoutInfo` to:

`    return numGroupDefeated, 0, 0, 0, numGroupDefeated, 0`

**Comment by 0xbs** [comment]
Thanks for pointing this out and already doing an analysis. Will release an update shortly.
