### ISSUE TITLE
Add a search for the name

### ISSUE THREAD

**Issue by nvareille** [0xbs/premade-groups-filter#27]
It could be great to allow the research for groups name (For key levels)

If I want to fetch for +10, typing something like '$name contains "+10"' would be awesome :)

**Comment by 0xbs** [comment]
This would be indeed great and has already been a feature of PGF. However, starting with the Battle for Azeroth Prepatch, the group name is protected by Blizzard and can no longer be evaluated by any addon. This is also already listed in the [FAQ](https://github.com/0xbs/premade-groups-filter/wiki/FAQ).

**Comment by nvareille** [comment]
Oh sorry for the useless issue then ...

Anyway great addon ! It helps me a lot !
