### ISSUE TITLE
Remove Skip Sign Up Dialog option and create an integrated dedicated section for Sign up Message and Role check

### ISSUE THREAD

**Issue by moisalucian** [0xbs/premade-groups-filter#270]
Hei, 

I know I did already some proposals, don't wanna be a pain in the ass, but I like what your addon does and I just feel it can be improved here an there with small tweaks.

I think that some people might wanna write a sign up message that can persist until changed, so I dedidated field area like the Advanced Filter Expression area is already would be usefull. 

People could write sign up messages and they will be persisted on all signup they do, until they will change the message or remove it.
Additionally there could be above or bellow this a checkbox with role selection, in case you wanna sign up for two roles at the same time, you can mark there DPS and Tank, or any other combination your class can do. 

![image](https://github.com/user-attachments/assets/4e1bc279-cac0-4928-8aa5-1e13a5f5eebb)
 An example here, but probably the message area could be a bit bigger. Or have an corner that can be extended, idk what's easier. 
 
 
![image](https://github.com/user-attachments/assets/989085b7-4381-45cb-b44f-9ac6d6d6a665)
Also here an image with raider io rating for the party lead. It seem way easier to see and cleaner for the user experience, In case you want to adapt it how it looks now :D

Thanks a lot again!

**Comment by 0xbs** [comment]
### Sign up message and roles

The sign up message is already being persisted until logout if you enable the "Persist Sign Up Note" option. After that, you may always change the message or role using Shift + Click on a group. I didn't want to waste screen space with input fields that almost never change and are not relevant most of the time.

![image](https://github.com/user-attachments/assets/7237ee07-5f3f-4fb4-8c32-2de5888bf0cc)

### Rating display

> Also here an image with raider io rating for the party lead. It seem way easier to see and cleaner for the user experience, In case you want to adapt it how it looks now :D

I think rating and max level in that dungeons looks quite clean in PGF. Also titles can be quite long in RGB and Arena where I also show a PvP rating, so simply adding the rating after the title would hide it in some cases. Prepending would be possible, but I never found that very aesthetically pleasing.

**Comment by moisalucian** [comment]
Ok, didn't knew about that with shift click. Thanks a lot! 

and about the rating display I had in mind only M+ where people write only +15 or so. Didn't think about the others, probably you are right
