### ISSUE TITLE
Diffculty is ignored

### ISSUE THREAD

**Issue by maphex** [0xbs/premade-groups-filter#278]
Difficulty filter is ignored when filtering raids. 
![image](https://github.com/user-attachments/assets/38a5c903-3302-4cc2-b7b1-52e34f7f2f10)

**Comment by 0xbs** [comment]
Thanks for the report. I will look into it, but I'm busy until next week.

**Comment by 0xbs** [comment]
Should be fixed in 6.0.3. Heroic was wrongly detected as normal.
