### ISSUE TITLE
When "show spec" toggle is on, visuals are broken

### ISSUE THREAD

**Issue by moisalucian** [0xbs/premade-groups-filter#279]
![image](https://github.com/user-attachments/assets/b4ea93a7-6750-4ee3-be40-8de28c2d190c)

Probably the image itself it's enough , not much explaination needed. Spec icons seems to be shifted, normal icons stil exists

**Comment by 0xbs** [comment]
You are using multiple addons to modify the group list, which does not work.

My addon does not change the icons themselves, but creates an overlay to avoid tainting and be more resilient to changes by Blizzard.

Another addon is moving the member icons to the left, so it looks kinda broken.

Just uninstall the other addon(s) and it will look fine. If they provide a feature I do not, please tell me and I will consider implementing it.

**Comment by moisalucian** [comment]
You are actually right, idk how that 2nd addon did activate. Excuse me :D
