### ISSUE TITLE
Delisted groups stuck in the list forever

### ISSUE THREAD

**Issue by hollo6** [0xbs/premade-groups-filter#281]
### Game Version
Retail

### Lua error from Bugsack
There is no LUA error.

### Screenshots
![image](https://github.com/user-attachments/assets/d7ba341d-0e76-4354-8d15-ece80528e860)

### Current behaviour
Groups that had been delisted (it seems only delisted, and not delisted_full) get stuck in the list.

### Steps to reproduce
1. Open premade dungeon list
2. Filters don't seem to matter
3. Apply to groups
4. Wait for some group to delist
5. Note they are still shown in the window, no matter how many times you refresh the list

### Expected behaviour
Delisted groups should not be shown after they delist.

**Comment by 0xbs** [comment]
I don't think this is a bug of PGF but rather Blizzard keeping those items in the list for an unknown reason. I don't actively remove delisted groups, they usually disappear by themselves on the next reload.

You may use e.g. `appstatus ~= "delisted"` to filter them out.

**Comment by hollo6** [comment]
Was a nice idea but does not work :(
![image](https://github.com/user-attachments/assets/1f818579-b52a-4ab7-827e-91a183073c62)

**Comment by hollo6** [comment]
This doesn't work either :(

![image](https://github.com/user-attachments/assets/0127e7e3-6c29-459a-84f2-ae1199a7afd1)

**Comment by 0xbs** [comment]
But there aren't any delisted groups in your screenshot?

**Comment by hollo6** [comment]
The ones that say Declined are actually delisted.

**Comment by hollo6** [comment]
This is what an actual decline looks like:
![image](https://github.com/user-attachments/assets/6cb4cc51-3b4f-47c7-9f8f-8d9e78635c26)
