### ISSUE TITLE
Only Mists, NW and Siege Keys?

### ISSUE THREAD

**Issue by Sebastian1989101** [0xbs/premade-groups-filter#282]
When PGF is active, the tool only yields Mists, NW and Siege Keys for me. When disabled I see other dungeons as well. I even tried without any filter except partyfit and this is still the case. Is there something broken with the new dungeons?

**Comment by 0xbs** [comment]
There seems to be a Blizzard bug that whenever you enter a search expression like "5-7", only dungeons from previous expansions are shown and TWW ones are missing.

PGF is not removing any new dungeons. You should see them same behavior with PGF on and off.

**Comment by 0xbs** [comment]
I opened Stanzilla/WoWUIBugs/issues/661 for further investigation.

**Comment by 0xbs** [comment]
Seems to be fixed with todays maintenance.
