### ISSUE TITLE
Advanced filter for dungeons not working

### ISSUE THREAD

**Issue by nasiqq** [0xbs/premade-groups-filter#283]
### Game Version
Retails

### Screenshots
![image](https://github.com/user-attachments/assets/930afbf0-bfaa-4ab4-9e2a-6dd3b6bf9e2c)

### Current behaviour
advanced filter is 
(tanks >=1 or heals>=1) and partyfit and (cot or nw)
however showing tirna and other dungeons as well

### Steps to reproduce
use filter above.

### Expected behaviour
is I filter with dungeons like (cot or nw) do not show anything else

**Comment by nasiqq** [comment]
also you can see a +8 with a single DPS , while in filter have tanks OR heal minimum 1..

**Comment by nasiqq** [comment]
Another thing is if I put a typo do the advanced filter having error message which is normal, but if I fix it, why having the same error message? 
![image](https://github.com/user-attachments/assets/4a348fe3-7c1b-499d-a18f-ee51d59caa12)

**Comment by 0xbs** [comment]
I tested your expression and it works perfectly fine for me. I see that you have another addon active that manipulates the premade dungeon list (there is an "options" button behind the PGF checkbox). Could it be the case that the other addon is doing a different filtering and prevents PGF from working correctly? Please try with just PGF and no other addon installed.

---

Regarding the typo issue, I just tried the following:

1. Using your expression, I added a w, making it `(tanks >=1 or heals>=1) wand partyfit and (cot or nw)`
2. I click somewhere else so the focus is lost on the text area
3. I see the error message popup
4. I click Okay
5. I correct the typo, removing the w
6. I click somewhere else so the focus is lost on the text area
7. No error message shown for me

So I'm not sure which issue you are having. Could you please be more precise and provide all steps like I did?

**Comment by 0xbs** [comment]
Oh if you mean that you get an error message when using `AND` in all uppercase letters, well that's because `AND` is not a valid but `and` is. The reason is that you are in fact programming in the language Lua, where only a lowercase `and` is defined as the logical conjunction operator. Programming languages are very picky about the casing of letters. I already thought about internally "lowercasing" your expression before sending it to the interpreter, but this would mean that I cannot use mixed-case expressions in the future.

**Comment by 0xbs** [comment]
>  Not sure if possible to implement a solution like if I click on search button, then re-read the text in the advanced filter and do not need to loose focus before that?

Acutally it works exactly like that for me. As soon as I click the Search button, the focus is lost and the search runs with the new expression. I will have a look if I cann add something to explicitly loose focus before the search happens.
