### ISSUE TITLE
Feature Request: Option for the M+ Rating colors to mirror those used by Raider.IO

### ISSUE THREAD

**Issue by deikun** [0xbs/premade-groups-filter#290]
Hello, I've noticed that the M+ score colors of the group leaders tend to be a bit off in relation to the ones used by Raider.IO, would it be possible to bring them more in line? I even attempted to turn off the colors used by R.IO and even the item quality style of colors were a good bit off. 

![image](https://github.com/user-attachments/assets/43d45a95-b821-4653-b417-2073af747568)

**Comment by 0xbs** [comment]
I could use the RIO color scheme if the RIO addon is loaded. Would you prefer to automatically have RIO colors in PGF if RIO is loaded or have an option to explicity turn it on?

**Comment by deikun** [comment]
Oh that may be a pretty nifty way of doing it. That would work too, but I'm also not sure what would be best for everyone. I do think the consistency of color across the user's experience is important regardless of which option you go with. I know that RIO client offers some toggles between the colors, it's either default colors, or simple item quality colors, or no colors at all.

**Comment by 0xbs** [comment]
I implemented it so that the colors automatically match the ones of rio. Version 6.4.0 should be distributed soon.
