### ISSUE TITLE
Having the addon enabled breaks "Report Advertisement"

### ISSUE THREAD

**Issue by xeropresence** [0xbs/premade-groups-filter#298]
Please check FAQ and existing issue first:
- FAQ / Wiki: https://github.com/0xbs/premade-groups-filter/wiki/FAQ
- All Issues: https://github.com/0xbs/premade-groups-filter/issues?q=

### Game Version
Retail 

### Lua error from Bugsack
n/a

### Screenshots
n/a

### Current behaviour

1)Right click
2)Click "Report Advertisement"
3)Have to click multiple more fields to submit the report

### Steps to reproduce
1) Have PGF installed

### Expected behaviour
1)Right click
2)Click "Report Advertisement"

**Comment by 0xbs** [comment]
See second entry in FAQ: https://github.com/0xbs/premade-groups-filter/wiki/FAQ
