### ISSUE TITLE
Support for Delves

### ISSUE THREAD

**Issue by bjmorden** [0xbs/premade-groups-filter#299]
Please check FAQ and existing issue first:
- FAQ / Wiki: https://github.com/0xbs/premade-groups-filter/wiki/FAQ
- All Issues: https://github.com/0xbs/premade-groups-filter/issues?q=

Would love for the Addon to work on the Delves Group Finder tab.

**Comment by 0xbs** [comment]
It already does. Just check the PGF checkbox on the top right of the group listing to enable PGF for Delves. The PGF window looks a bit different, but should work as on other categories.

**Comment by bjmorden** [comment]
wow, I am blind.  Thank you for pointing that out.
