### ISSUE TITLE
Filter for raids with exactly the same defeated bosses as the player

### ISSUE THREAD

**Issue by 0xbs** [0xbs/premade-groups-filter#3]
Feature request for a filter function that shows only dungeons that have the same lockout than the player which is searching. E.g. if the player has defeted the first boss X of a raid, only groups which have defeated X but not any other bosses should be shown.

**Comment by Coalado** [comment]
good idea. Or  add an alive=bossa,bossb,bossc ,...  filter option

**Comment by 0xbs** [comment]
The new boolean `matchingid` as well as the new integer variables `bossesmatching`, `bossesahead` and `bossesbehind` should resolve this feature request.
