### ISSUE TITLE
Tank OR Healer >0

### ISSUE THREAD

**Issue by dawn-star** [0xbs/premade-groups-filter#302]
I'm not sure if this is already possible with existing expressions, great if someone could advise on how to do it if so.

I'd love to be able to see only groups that have a Tank OR a Healer in the group already, would that be doable?

**Comment by 0xbs** [comment]
Sure! I assume that you mean an exclusive 'or' (either tank or heal but not both).

If you are targeting dungeon groups, you could use the fact that there is only one heal and one tank at max and use:
```lua
tanks + heals == 1
```
This will show only groups where there is one heal or one tank, but not both and also not zero of them.

More complicated, but equivalent would be:
```lua
(( tanks == 0 and heals == 1 ) or (tanks == 1 and heals == 0 ))
```
Braces are optional in this case as `and` comes before `or` just like multiplication before addition.


For raid groups, this is getting a bit more difficult. Usually there are two tanks, but there could be more healers.
You start with the following and make it more complicated as you need:

```lua
( tanks == 1 or ( tanks == 0 and heals >= 1 ))
```
This means either exactly one tank or at least one heal.

**Comment by dawn-star** [comment]
`(( tanks == 0 and heals == 1 ) or (tanks == 1 and heals == 0 ))`

This is exactly what I was looking for, thank you so much!
