### ISSUE TITLE
Feature: Add the ability to filter out based on group leader server.

### ISSUE THREAD

**Issue by Cistoran** [0xbs/premade-groups-filter#33]
Example 

> not server("thrall") 

Would filter out all groups where the group leader is on Thrall. Not sure if each group member's server  is exposed in a way that could be filtered but if that's possible it would be even better.

**Comment by 0xbs** [comment]
This is already possible using `not leader:find("doomhammer")` for filtering group leaders from Doomhammer or `not myrealm` to filter players from your own realm. This works because the player names have the realm as a suffix except when they are from your own realm.
