### ISSUE TITLE
RaiderIO code update

### ISSUE THREAD

**Issue by Kanegasi** [0xbs/premade-groups-filter#34]
Date: 2020-09-19 13:18:40
ID: 1
Error occured in: Global
Count: 2
Message: ...face\AddOns\PremadeGroupsFilter\Plugins\RaiderIO.lua line 52:
   attempt to call field 'HasPlayerProfile' (a nil value)
Debug:
   [string "@PremadeGroupsFilter\Plugins\RaiderIO.lua"]:52: ?()
   [string "@PremadeGroupsFilter\Main.lua"]:416:
      PremadeGroupsFilter\Main.lua:272
   [string "=[C]"]: LFGListUtil_SortSearchResults()
   [string "@..\FrameXML\LFGList.lua"]:1791: LFGListSearchPanel_UpdateResultList()
   [string "@..\FrameXML\LFGList.lua"]:1675: onEvent()
   [string "@..\FrameXML\LFGList.lua"]:218:
      ..\FrameXML\LFGList.lua:132

**Comment by 0xbs** [comment]
I just downloaded RaiderIO-v202009190600 and the function HasPlayerProfile still exists and has not changed. Before I buy a month of WoW to check myself, are you sure that the API changed and what version of Raider.IO are you using?

**Comment by Kanegasi** [comment]
It seems RaiderIO is doing a bunch of changes and feeding them into the client updates. I have v202009191822 installed from their client which updates every three hours for me. I can confirm that the current Curse version has that function but the one I have does not. In fact, there's only one spot in core.lua that still has it. You may need to wait for the Curse version to come out tomorrow.

**Comment by aromagnoli** [comment]
![image](https://user-images.githubusercontent.com/4464751/93691247-fa63ea80-fab8-11ea-8473-ff3c3e1bbd92.png)
As per today, Raider.IO api changed and broke the addon. Source: 
![image](https://user-images.githubusercontent.com/4464751/93691263-22ebe480-fab9-11ea-992e-560bfd9ac0b1.png)

**Comment by Kanegasi** [comment]
Here's the message linked in that announcement:

> Changes I have noticed so far that may impact addons or WeakAuras that used the public functions from the RaiderIO Addon Namespace:
>     -  `GetPlayerProfile` function it has been renamed to `GetProfile`
>     - `GetProfile` been updated to require a minimum of 3 arguments
>         - `name` (string)
>         - `realm` (Normalized)
>             You can use Blizzards `GetNormalizedRealmName()` to get your own.
>             This is needed if you are looking up IO from players listed in LFG search results if that player is on your realm.
>         - `faction` (int)
>             Alliance = 1
>             Horde = 2
>             Neutral = 3
>     - The data structure returned back from `GetProfile` has been changed
>     `{
>             success = (mythicKeystoneProfile or raidProfile or pvpProfile) and true or false,
>             guid = guid,
>             name = name,
>             realm = realm,
>             faction = faction,
>             region = region,
>             mythicKeystoneProfile = mythicKeystoneProfile,
>             raidProfile = raidProfile,
>             pvpProfile = pvpProfile
>          }`
>     - `mythicKeystoneProfile` has the  `mplusCurrent` table under it.

**Comment by niczak** [comment]
I just submitted a pull request with a fix for this issue, I have a local copy of the addon with the change and it is back working.

**Comment by 0xbs** [comment]
Thank you for the information. So clients in the wild do now have two different RaiderIO APIs, either because they did not yet update or because they are using the CurseForge version. Ugh.

**Comment by cuddeford** [comment]
This is affecting my game client too. It throws the error when I search in the group finder and then the filters stop working.

**Comment by 0xbs** [comment]
Alright, PGF now supports both the old and the new RaiderIO. They changed more than I thought. I would rather not support RaiderIO since it makes WoW and PUGs an unpleasant game, but I see why it was invented in the first place and it is really popular among players. So here you go.
