### ISSUE TITLE
1.38 is not associated with any game versions

### ISSUE THREAD

**Issue by layday** [0xbs/premade-groups-filter#36]
The `gameVersion` array for version 1.38 from the [API](https://addons-ecs.forgesvc.net/api/v2/addon/102896/file/3061514) is empty.  I assume this is why it is not available for download from CF or the Twitch client.  Did you select 8.3.0 when you uploaded the file?

**Comment by layday** [comment]
Well, it seems to work now, though `gameVersion` is still empty 🤷

**Comment by 0xbs** [comment]
The reason for the delay was simply that CurseForge has to approve every single package. Usually they are very fast, but this time it took time than usual.
I also do not upload the file myself. Whenever I tag a version in git, GitHub automatically triggers a Webhook which automatically triggers packaging and distribution on CurseForge. I also never set the gameVersion myself, this is done by CurseForge with the current version or maybe they read the version in the toc file.

**Comment by layday** [comment]
Something must've gone wrong on their end then I suppose for the `gameVersion` array to be empty.
