### ISSUE TITLE
activityname:find errors

### ISSUE THREAD

**Issue by ztnko** [0xbs/premade-groups-filter#41]
https://puu.sh/GKZFs/cd84b36cfc.png
https://puu.sh/GKZFW/ffd11e8af4.png

doesn't matter what i put in activityname:find("xxx") - it's errors. how to use it?

**Comment by Ugo-G** [comment]
Apparently this is no longer possible since BFA : 

https://github.com/0xbs/premade-groups-filter/wiki/FAQ#how-can-i-exclude-groups-with-wts-or-boost-in-the-name

**Comment by 0xbs** [comment]
Searching by activityname should still work (name and comment do not). The `find` function returns `nil` if no result was found, so try to use e.g. `activityname:find("dungeon")~=nil` for searching for the word "dungeon". Note that you have to keep it all lower case and that the acitivity name is just the gray text underneath the title (yellow text in tooltip).
