### ISSUE TITLE
Filter by armor type

### ISSUE THREAD

**Issue by sm1rks** [0xbs/premade-groups-filter#43]
Would be nice to be able to sort groups by how many of an armor type they have, like more than 2 leathers or something like that. Makes it easier to get potential gear traded or trade to others in PUGs.

**Comment by Ugo-G** [comment]
- **For 4 plate :** 

((warriors == 4)    or
(paladins == 4)    or
(deathknights == 4)    or
(warriors == 3 and paladins == 1)    or
(warriors == 3 and deathknights == 1)    or
(paladins == 3 and warriors == 1)    or
(paladins == 3 and deathknights == 1)    or
(deathknights == 3 and warriors == 1)    or
(deathknights == 3 and paladins == 1)    or
(warriors == 2 and paladins == 2)    or
(warriors == 2 and deathknights == 2)    or
(warriors == 2 and paladins == 1 and deathknights == 1)    or
(paladins == 2 and deathknights == 2)    or
(paladins == 2 and warriors == 1 and deathknights == 1)    or
(deathknights == 2 and warriors == 1 and paladins == 1))    


- **For 3+ plate :** 

((warriors >= 3)    or
(paladins >= 3)    or
(deathknights >= 3)    or
(warriors >= 2 and paladins >= 1)    or
(warriors >= 2 and deathknights >= 1)    or
(paladins >= 2 and warriors >= 1)    or
(paladins >= 2 and deathknights >= 1)    or
(deathknights >= 2 and warriors >= 1)    or
(deathknights >= 2 and paladins >= 1)    or
(deathknights >= 1 and warriors >= 1 and paladins >= 1))    


- **For 2+ plate :**

((warriors >= 2)    or
(paladins >= 2)    or
(deathknights >= 2)    or
(warriors >= 1 and paladins >= 1)    or
(warriors >= 1 and deathknights >= 1)    or
(paladins >= 1 and deathknights >= 1))    


- **For 4 leather :**

((druids == 4)    or
(druids == 3 and rogues == 1)    or
(druids == 3 and demonhunters == 1)    or
(druids == 3 and monks == 1)    or
(druids == 2 and rogues == 2)    or
(druids == 2 and monks == 2)    or
(druids == 2 and demonhunters == 2)    or
(druids == 2 and rogues == 1 and monks == 1)    or
(druids == 2 and rogues == 1 and demonhunters == 1)    or
(druids == 2 and monks == 1 and demonhunters == 1)    or
(druids == 1 and rogues == 3)    or
(druids == 1 and monks ==3)    or
(druids == 1 and demonhunters == 3)    or
(druids == 1 and rogues == 2 and monks == 1)    or
(druids == 1 and rogues == 2 and demonhunters == 1)    or
(druids == 1 and monks == 2 and rogues == 1)    or
(druids == 1 and monks == 2 and demonhunters == 1)    or
(druids == 1 and demonhunters == 2 and rogues == 1)    or
(druids == 1 and demonhunters == 2 and monks == 1)    or
(druids == 1 and rogues == 1 and monks == 1 and demonhunters == 1)    or
(rogues == 4)    or
(rogues == 3 and monks == 1)    or
(rogues == 3 and demonhunters == 1)    or
(rogues == 2 and monks == 2)    or
(rogues == 2 and demonhunters == 2)    or
(rogues == 2 and monks == 1 and demonhunters == 1)    or
(rogues == 1 and monks == 3)    or
(rogues == 1 and demonhunters == 3)    or
(rogues == 1 and monks == 2 and demonhunters == 1)    or
(rogues == 1 and demonhunters == 2 and monks == 1)    or
(monks == 4)    or
(monks == 3 and demonhunters == 1)    or
(monks == 2 and demonhunters == 2)    or
(monks == 1 and demonhunters == 3)    or
(demonhunters == 4))    


- **For 3+ leather :**

((druids >= 3)    or
(monks >= 3)    or
(rogues >= 3)    or
(demonhunters >= 3)    or
(druids >= 2 and monks >= 1)    or
(druids >= 2 and rogues >= 1)    or
(druids >= 2 and demonhunters >= 1)    or
(monks >= 2 and druids >= 1)    or
(monks >= 2 and rogues >= 1)    or
(monks >= 2 and demonhunters >= 1)    or
(rogues >= 2 and druids >= 1)    or
(rogues >= 2 and monks >= 1)    or
(rogues >= 2 and demonhunters >= 1)    or
(demonhunters >= 2 and druids >= 1)    or
(demonhunters >= 2 and monks >= 1)    or
(demonhunters >= 2 and rogues >= 1)    or
(demonhunters >= 1 and rogues >= 1 and monks >= 1)    or
(demonhunters >= 1 and rogues >= 1 and druids >= 1)    or
(monks >= 1 and rogues >= 1 and druids >= 1)    or
(demonhunters >= 1 and monks >= 1 and druids >= 1))    


- **For 2+ leather :**

((druids >= 2)    or
(monks >= 2)    or
(demonhunters >= 2)    or
(rogues >= 2)    or
(druids >= 1 and monks >= 1)    or
(druids >= 1 and demonhunters >= 1)    or
(druids >= 1 and rogues >= 1)    or
(rogues >= 1 and monks >= 1)    or
(rogues >= 1 and demonhunters >= 1)    or
(monks >= 1 and demonhunters >= 1))    


- **For 4 cloth :**

((mages == 4)    or
(priests == 4)    or
(warlocks == 4)    or
(mages == 3 and priests == 1)    or
(mages == 3 and warlocks == 1)    or
(priests == 3 and mages == 1)    or
(priests == 3 and warlocks == 1)    or
(warlocks == 3 and mages == 1)    or
(warlocks == 3 and priests == 1)    or
(mages == 2 and priests == 2)    or
(mages == 2 and warlocks == 2)    or
(mages == 2 and priests == 1 and warlocks == 1)    or
(priests == 2 and warlocks == 2)    or
(priests == 2 and mages == 1 and warlocks == 1)    or
(warlocks == 2 and mages == 1 and priests == 1))    


- **For 3+ cloth :**

((mages >= 3)    or
(priests >= 3)    or
(warlocks >= 3)    or
(mages >= 2 and priests >= 1)    or
(mages >= 2 and warlocks >= 1)    or
(priests >= 2 and mages >= 1)    or
(priests >= 2 and warlocks >= 1)    or
(warlocks >= 2 and mages >= 1)    or
(warlocks >= 2 and priests >= 1)    or
(warlocks >= 1 and mages >= 1 and priests >= 1))    


- **For 2+ cloth :**

((mages >= 2)    or
(priests >= 2)    or
(warlocks >= 2)    or
(mages >= 1 and priests >= 1)    or
(mages >= 1 and warlocks >= 1)    or
(priests >= 1 and warlocks >= 1))

**Comment by Ugo-G** [comment]
- **For 4 mail :**

((hunters == 4)	or
(shamans == 4)	or
(hunters == 1 and shamans == 1)	or
(shamans == 1 and hunters == 1)	or
(hunters == 1 and shamans == 1))	


- **For 3+ mail :**

((hunters >= 3)	or
(shamans >= 3)	or
(hunters >= 2 and shamans >= 1)	or
(shamans >= 2 and hunters >= 1))	


- **For 2+ mail:**

((hunters >= 2)	or
(shamans >= 2)	or
(shamans >= 1 and hunters >= 1))

**Comment by 0xbs** [comment]
I added keywords plate, mail, leather and cloth for number of chars with this armor type in the group.
