### ISSUE TITLE
Myrealm flag not working

### ISSUE THREAD

**Issue by samfishersam** [0xbs/premade-groups-filter#44]
Hi everyone, been trying to get the myrealm flag to work on version 2.0.1 but it doesn't seem to be working?  Did Blizzard change how you can detect realms, or is this a user error and I'm just dumb?

`tanks >=1 or heals >=1 and mythic and partyfit and myrealm`

**Comment by 0xbs** [comment]
It works as expected (although I noticed an error popping up sometimes, which I already fixes).
The problem in you expression is that you did not wrap the `or`-statement in braces. The operator `and` has higher precedence than `or`, just like multiplication is done before addition in maths.

So LUA thinks you want to say
`tanks >=1 or (heals >=1 and mythic and partyfit and myrealm)`
which means that it is fine to include groups from other realms if they have at least one tank.

But you really want to say this:
`(tanks >=1 or heals >=1) and mythic and partyfit and myrealm`

**Comment by samfishersam** [comment]
Hi, thank you for that!  Would also like to ask if there is a way to filter by groups of realms?  Like including only Oceanic only realms, or listing one by one the servers that are included in the search?

**Comment by 0xbs** [comment]
Yes, please have a look at the FAQ: https://github.com/0xbs/premade-groups-filter/wiki/FAQ#is-there-a-filter-for-oceanic-realms This question and also your original question has already been asked many times.
