### ISSUE TITLE
Filter mythicplus title by key values

### ISSUE THREAD

**Issue by iankoetter** [0xbs/premade-groups-filter#48]
For mythic plus, it would be nice to use OR logic to filter for keywords when looking for specific mythic plus levels. Sometimes you want to run a specific level and could stand to filter out all those too far above or below your range. Since this is only listed in the freeform title, you'd have to filter against it.
Examples:
`sd and title == (8 or 9 or 10)`
matches
"+8 SD" and "9" and "mythic 10 tank" but not "+13" or "15+ sd"

`pf and title > 6`
matches
"6+ plaguefall" and "+10 pf" but not "4 pf" or "m+3 plaguefall" or "m0 plaguefall"

**Comment by 0xbs** [comment]
Please read the FAQ:

> This is no longer possible. Starting with the Battle for Azeroth Prepatch, the group name is protected by Blizzard and can no longer be evaluated by any addon.

But Blizzards default search above the group list offers sort of what you want. Just type e.g. `plaguefall 10` and you will only get search results or Plaguefall 9, 10 and 11. This behavior cannot be customized however.
