### ISSUE TITLE
[request] filter for classes

### ISSUE THREAD

**Issue by makedir** [0xbs/premade-groups-filter#49]
Please implement filters for classes. For example:

1 tank which is class x
+
containing at least 1 class of y
+
containing at least 1 class of z

**Comment by 0xbs** [comment]
This is already possible. Have a look at the [full list of keywords](https://github.com/0xbs/premade-groups-filter/wiki/Keywords). You may e.g. use `warrior_tanks`, `paladin_heals` etc.

**Comment by makedir** [comment]
Oh wow, thats awesome! Thank you very much!
