### ISSUE TITLE
Addon Button/Macro Option to open the Group Finder Frame

### ISSUE THREAD

**Issue by Coalado** [0xbs/premade-groups-filter#5]
It would be great to write Macros that  open the group finder Frame and init a search.
I managed to open the frame by 

/run if not GroupFinderFrame:IsVisible() then PVEFrame_ShowFrame("GroupFinderFrame") end
/click GroupFinderFrameGroupButton4
/run LFGListCategorySelection_SelectCategory(LFGListFrame.CategorySelection,2,0)
/run LFGListCategorySelectionFindGroupButton_OnClick(LFGListFrame.CategorySelection.FindGroupButton)

But PGF filter fails. I have to manually activate/deactivate it in order to filter properly.
It would be great if you could add an option  for this to save some clicks

**Comment by 0xbs** [comment]
Should be fixed in one of the last alpha versions. Check out e.g. [1.10-5-g67bc4d4-alpha](https://wow.curseforge.com/projects/premade-groups-filter/files).

**Comment by Coalado** [comment]
works fine
