### ISSUE TITLE
Diffrent results after each refresh

### ISSUE THREAD

**Issue by crtl** [0xbs/premade-groups-filter#54]
When using the addon many times you will get diffrent results for applying the same query.
For example:
`mythic`
`mythic and tanks <= 0`

This does not happen because the grps expire because after refreshing a random amount of time you will see the same groups sooner or later again.

Also it feels like the difficulty filter is not working properly.

Addon version is 2.1.1.

**Comment by 0xbs** [comment]
For future reference: also see the [FAQ](https://github.com/0xbs/premade-groups-filter/wiki/FAQ#why-are-results-sometimes-disappearing-when-using-the-searchreload-button-multiple-times) why it behaves like that.
