### ISSUE TITLE
[Feature Request] Filter by keystone difficulty

### ISSUE THREAD

**Issue by crtl** [0xbs/premade-groups-filter#55]
It would be nice to be able to filter by keystone difficulty/level for example:

`mythicplus and klvl >= 10`

**Comment by 0xbs** [comment]
Would be nice ideed, but not possible. There is no designated field for the difficulty. Instead, people write the difficulty in the title. The title however is protected and cannot be read by any addon. Also see #48 and please read the [FAQ](https://github.com/0xbs/premade-groups-filter/wiki/FAQ#how-can-i-search-for-mythic-dungeons-with-a-certain-difficulty-eg-10).
