### ISSUE TITLE
Feature request: Filter by dungeon

### ISSUE THREAD

**Issue by chadmccune** [0xbs/premade-groups-filter#59]
Title is self explanatory :)

Ideally, you could just put check marks next to the dungeon(s) you're looking for.  This would be useful, if you're searching for a M+ key of a certain level for several dungeons at once.

**Comment by 0xbs** [comment]
It is possible to filter by multiple dungeons using keywords (see list of all keywords). Please have a look at the [first two FAQ entries](https://github.com/0xbs/premade-groups-filter/wiki/FAQ) why I am currently not planning to add checkboxes for dungeons.
