### ISSUE TITLE
Feature request - "and not ${regionId}realm"

### ISSUE THREAD

**Issue by YoungP036** [0xbs/premade-groups-filter#62]
We know which servers are associated with which each region via [realm wiki page](https://wowwiki-archive.fandom.com/wiki/Realms_list). Would you consider adding variables to the advanced expression query such that someone who is playing NA could write the below expression to filter out oceanic and latin american groups? 

`not ocerealm and not larealm`

I think the best we can do is use the group leaders realm to categorize the group, since I don't know if we can introspect the party members. If we can inspect all party members then we could classify each party member in to a region, and whichever region dominates the group would become the classification for the group itself. Either option would be great, though.

I believe the hard separation of regions is NA, EU, and Asia. However, within NA we have the below categories. There may be a similar situation in EU and Asia regions, but I am not from those regions so I cannot speak to that.

- naestrealm - eastern NA
- nacstrealm - central NA
- nawstrealm - western NA
- larealm - Central and South America(not sure on the exact server locations, but the ping gets dicy when EST NA and CA/SA mix)
- ocerealm - Oceanic(extremely dicy pings when OCE and EST NA mix)

**Comment by 0xbs** [comment]
An oceanic player and me made the addon Premade Regions which does exactly what you describe. You find links to it in the readme or in the full list of keywords in the wiki.

**Comment by YoungP036** [comment]
Nice, you are a legend sir
