### ISSUE TITLE
Can't you search plain text of the title/description?

### ISSUE THREAD

**Issue by epigramx** [0xbs/premade-groups-filter#63]
If this feature doesn't exist it seems like a crucial omission. I suggest to be denoted by quotations (e.g. "16" or "sylv").

**Comment by 0xbs** [comment]
Searching the title or description is no longer possible. Starting with the Battle for Azeroth Prepatch, the group name was protected by Blizzard and can no longer be evaluated by any addon. See FAQ.

**Comment by epigramx** [comment]
Their decision makes no sense. What are they trying to protect? Resources usage?

**Comment by 0xbs** [comment]
Not entirely sure. I think it was to block addons like World Quest Group Finder which did automatically search and join a group in the background. These addons caused massive server load, hence they blocked automatic searches, group joining and also text analysis. Actually blocking automatic background searches should have been enough, not sure why they blocked access to group names. Maybe data protection, maybe to prevent some other use case I do not know. The only other blocked information until then was the Battle.net ID which did make sense to prevent cross-char tracking.

**Comment by 0xbs** [comment]
What bugs me even more is that they also protected the default search box above the group listing. You cannot paste into it via CTRL+C and also addons are unable to set up a search text.

**Comment by epigramx** [comment]
I guess they tried to nuke all possibilities of automatic joining, most probably because they don't want UI-experienced players to have big advantages compared to the rest.
I don't get why they would nuke things that would need a manual search though; they wouldn't be huge advantage; maybe their system is bad and can't separate them.
