### ISSUE TITLE
[Feature Request] Add regular expression/ `string.match` support

### ISSUE THREAD

**Issue by 3axap4eHko** [0xbs/premade-groups-filter#66]
It's really the best addon to filter groups!
But I feel a lack of regexp support when I need to find a group for a specific key or pvp rating.
For example, I want to find M+2 key party, but the current wow interface will output to me all parties that have `2` in titles, like `22+` or `4x2 farm` or `2 last slots` or even `123123123123`.
It would be great if I can use something like `title.match("\b2\b")` what will find a group with the exact single number `2` in the description

**Comment by 0xbs** [comment]
Sadly not possible anymore. Searching and matching the title was a feature of PGF until BfA. Starting with the Battle for Azeroth Prepatch, the group name and comment is protected by Blizzard and can no longer be evaluated by any addon. I can only speculate about the reasons but assume it was done most likely to stop addons from performing automatic group searches and joins like World Quest Group Finder.
