### ISSUE TITLE
arena rating

### ISSUE THREAD

**Issue by masterkain** [0xbs/premade-groups-filter#69]
thanks for the addon, I use it to shave the list of arena groups.

would it be possible to include a filter to match the rating?

**Comment by masterkain** [comment]
I guess mprating  > 1700 works

**Comment by masterkain** [comment]
actually it does not, sorry

**Comment by masterkain** [comment]
thanks for 2.5.0, I installed but I often I get an error with this query `warriors == 0 and pvprating >= 1950` attempt to compare number with nil

it doesn't happen 100% of the times, should I use another expression>

**Comment by 0xbs** [comment]
Thank you for your report and bringing this to my attention. You are right, it seems that there is no PvP rating information for some groups. Fixed in 2.5.1.
