### ISSUE TITLE
Advanced expression using OR 

### ISSUE THREAD

**Issue by elvador** [0xbs/premade-groups-filter#7]
Using an advanced expression like this results in a query like `(ilvl >= 905 and bosses <= 0 and nh) or en` where it should be `ilvl >= 905 and bosses <= 0 and (nh or en)` imo. 
![wow-64_2017-07-01_16-32-39](https://user-images.githubusercontent.com/8883045/27762936-f4bb67bc-5e7a-11e7-9575-27ddfa22fa97.png)

**Comment by 0xbs** [comment]
On the one hand you are right, on the other hand this allows concatenating an OR-expression via `true or (...)`. Which could also be done with a solo advanced expression. 

Also I wonder if this will break some existing filters set up by players.

**Comment by elvador** [comment]
Yeah, it could stay that way, just have to put braces around the expression. 

I only recently noticed that this works (despite using the addon for months now), because I always thought the advanced expression "overrides" the other filters.

**Comment by 0xbs** [comment]
I thought a lot about how to communicate that all selected filters including the advanced expression are combined using the logical AND (with the small exception of the second item level checkbox), but found no good way to do that in two small lines. Also I know that the gray colored text in the advanced expression box (which shows the current UI configuration in LUA) might lead to the conclusion that the box can't be used together with the other options but was meant to show unexperienced players how an advanced expression does look like. And I think/hope it helps a lot.

So I think I just keep it like that for now and close the ticket.
