### ISSUE TITLE
Use Search Field

### ISSUE THREAD

**Issue by Coalado** [0xbs/premade-groups-filter#8]
I know that blizzard returns only 50 results, and that filtering is done clientside.
Would it be possible to add a field searchfield:name("tos")  that uses the main searchfield and thus does filtering on serverside?

**Comment by Coalado** [comment]
May even use the language prefilters as well

**Comment by Coalado** [comment]
The searchfield thingy can be faked by using
`/run LFGListFrame.SearchPanel.SearchBox:SetText("Grabmal des Sargeras (Heroisch)")`

I did not find and easy way for the languages

**Comment by 0xbs** [comment]
Where do you see the advantage over entering the term into the search field directly? It could be helpful if you are constantly switching between e.g. dungeon and raid searches, but apart from that?

**Comment by Coalado** [comment]
I'm looking for "name==tos heroic heal<3 tanks>0 dmg>5 bossesbehind==0 bossesahead==0 
there are not many that match these filters. and wow does not return 50 matches.

if i search for tos in the searchfield instead, I get much more matches . Am I wrong?

**Comment by Coalado** [comment]
short: if name filtering is done serverside, I might get more matches

**Comment by 0xbs** [comment]
Right. You get more results if you set up a server side ToS filter via the default search field and its dropdown menu. But where is the difference between typing ToS in the default search field and typing ToS into the advanced expression box?

My reasons for keeping it separated:

- you have a clear separation between server side filter (default search box) and client side filtering (addon window)
- if there is already something in the default search field and you use the proposed searchfield keyword, which one has higher priority?

**Comment by Coalado** [comment]
I have macros for everything I need. And I'd like to keep things simple with one click. at the moment, I have to enter text in the searchbox and click my macro afterwards.
with a searchfield keyword, this would be only one click.
the searchfield keyword should have higher priority.

but... I'm actually fine with my workaround
