### ISSUE TITLE
Match tazavesh filters with Raider IO acronyms

### ISSUE THREAD

**Issue by LacrouxNathan** [0xbs/premade-groups-filter#82]
Simply change tazavesh filter to match with Raider IO :

- `tazs` -> `strt`
- `tazg` -> `gmbt`

Also add those filters in the tooltip

**Comment by xKukkai** [comment]
That's what I wanted to ask. I totally agree with this request.

**Comment by 0xbs** [comment]
Is there a page where I can see the Raider.IO acronyms?

**Comment by LacrouxNathan** [comment]
You can see it when you hover dungeons on character page :
https://raider.io/characters/eu/tarren-mill/Gingitwo

Also you can see them in game
![Capture](https://user-images.githubusercontent.com/36017013/159120860-032f213c-66ce-4dd9-b321-aaaee9b18c80.PNG)

**Comment by 0xbs** [comment]
New aliases `strt` and `gmbt` have been added in version 2.7.2.
I won't change the tooltip though as I like my keywords better and it is already full enough.
