### ISSUE TITLE
Error using Addon with TSM: Attempt to index local 'afixIDs' (a nil value)

### ISSUE THREAD

**Issue by Skullcan** [0xbs/premade-groups-filter#84]
I don't know if this is a problem you guys can fix, reporting here just in case.

Message: ...ce\AddOns\PremadeGroupsFilter\Modules\PlayerInfo.lua:46: attempt to index local 'affixIDs' (a nil value)
Time: Thu Mar 24 22:04:13 2022
Count: 3
Stack: ...ce\AddOns\PremadeGroupsFilter\Modules\PlayerInfo.lua:46: attempt to index local 'affixIDs' (a nil value)
[string "@Interface\AddOns\TradeSkillMaster\LibTSM\Service\ErrorHandler.lua"]:761: in function <...Ons\TradeSkillMaster\LibTSM\Service\ErrorHandler.lua:717>
[string "=[C]"]: ?
[string "@Interface\AddOns\PremadeGroupsFilter\Modules\PlayerInfo.lua"]:46: in function `GetThisWeeksAffixNameLocalized'
[string "@Interface\AddOns\PremadeGroupsFilter\Modules\PlayerInfo.lua"]:65: in function `GetPlayerInfo'
[string "@Interface\AddOns\PremadeGroupsFilter\Main.lua"]:333: in function <Interface\AddOns\PremadeGroupsFilter\Main.lua:319>
[string "=[C]"]: ?
[string "=[C]"]: in function `LFGListUtil_SortSearchResults'
[string "@Interface\FrameXML\LFGList.lua"]:2068: in function `LFGListSearchPanel_UpdateResultList'
[string "@Interface\FrameXML\LFGList.lua"]:1998: in function <Interface\FrameXML\LFGList.lua:1997>
[string "=[C]"]: ?
[string "=[C]"]: in function `Show'
[string "@Interface\FrameXML\UIParent.lua"]:3017: in function `SetUIPanel'
[string "@Interface\FrameXML\UIParent.lua"]:2862: in function `ShowUIPanel'
[string "@Interface\FrameXML\UIParent.lua"]:2730: in function <Interface\FrameXML\UIParent.lua:2726>
[string "=[C]"]: in function `SetAttribute'
[string "@Interface\FrameXML\UIParent.lua"]:3582: in function `ShowUIPanel'
[string "@Interface\FrameXML\PVEFrame.lua"]:130: in function <Interface\FrameXML\PVEFrame.lua:91>
[string "=[C]"]: in function `PVEFrame_ShowFrame'
[string "@Interface\FrameXML\PVEFrame.lua"]:88: in function `PVEFrame_ToggleFrame'
[string "TOGGLEGROUPFINDER"]:1: in function <[string "TOGGLEGROUPFINDER"]:1>

Locals: errMsg = "...ce\AddOns\PremadeGroupsFilter\Modules\PlayerInfo.lua:46: attempt to index local 'affixIDs' (a nil value)"
isBugGrabber = nil
tsmErrMsg = nil
oldModule = nil
private = <table> {
 globalNameTranslation = <table> {
 }
 FormatErrorMessageSection = <function> defined @Interface\AddOns\TradeSkillMaster\LibTSM\Service\ErrorHandler.lua:517
 ErrorHandler = <function> defined @Interface\AddOns\TradeSkillMaster\LibTSM\Service\ErrorHandler.lua:134
 origErrorHandler = <function> defined @Interface\SharedXML\SharedBasicControls.lua:355
 hitInternalError = false
 CreateErrorFrame = <function> defined @Interface\AddOns\TradeSkillMaster\LibTSM\Service\ErrorHandler.lua:536
 num = 0
 SanitizeString = <function> defined @Interface\AddOns\TradeSkillMaster\LibTSM\Service\ErrorHandler.lua:510
 AddonBlockedHandler = <function> defined @Interface\AddOns\TradeSkillMaster\LibTSM\Service\ErrorHandler.lua:502
 GetStackLevelInfo = <function> defined @Interface\AddOns\TradeSkillMaster\LibTSM\Service\ErrorHandler.lua:344
 ParseLocals = <function> defined @Interface\AddOns\TradeSkillMaster\LibTSM\Service\ErrorHandler.lua:396
 ignoreErrors = false
 errorReports = <table> {
 }
 IsTSMAddon = <function> defined @Interface\AddOns\TradeSkillMaster\LibTSM\Service\ErrorHandler.lua:478
 localLinesTemp = <table> {
 }
 GetStackInfo = <function> defined @Interface\AddOns\TradeSkillMaster\LibTSM\Service\ErrorHandler.lua:313
}
MAX_STACK_DEPTH = 50
OLD_TSM_MODULES = <table> {
 1 = "TradeSkillMaster_Accounting"
 2 = "TradeSkillMaster_AuctionDB"
 3 = "TradeSkillMaster_Auctioning"
 4 = "TradeSkillMaster_Crafting"
 5 = "TradeSkillMaster_Destroying"
 6 = "TradeSkillMaster_Mailing"
 7 = "TradeSkillMaster_Shopping"
 8 = "TradeSkillMaster_Vendoring"
 9 = "TradeSkillMaster_Warehousing"
}

**Comment by 0xbs** [comment]
Thank you for the bug report, it was very helpful! Issue is fixed in version 2.8.1.
