### ISSUE TITLE
[Feature request] Add "Confirm" dialog to "Reset" button

### ISSUE THREAD

**Issue by Moonbloom** [0xbs/premade-groups-filter#85]
Please, for the love of all that is holy and pure in this world, add a 'Confirm' dialog to the 'Reset' button.
I can't count the amount of times that i've accidentally reset the advanced expression query (which i use exclusively), and lost 10+ queries, each multiple lines.

Or make it an option, so people who want can keep the existing functionality (i wouldn't understand why though)

**Comment by ChrisKader** [comment]
Good alternative to this is to require a modifier to be used when clicking the reset button (like SHIFT or ALT).

**Comment by 0xbs** [comment]
Better late than never, I implemented your request. It really sucks when you accidently click the button.
