### ISSUE TITLE
Bug: Authenticator

### ISSUE THREAD

**Issue by SuperChronos** [0xbs/premade-groups-filter#86]
If you do not have a Blizzard Authenticator attached to your account, you aren't allowed to make custom group names. Blizzard just gives you a basic +(whatever key level) in title. With Premade Group Filter addon enabled, it doesn't auto fill the title with a group name which in turn, doesn't allow you to list groups at all.

**Comment by SuperChronos** [comment]
![image](https://user-images.githubusercontent.com/86042561/161904410-2c7dee3c-149d-414a-acbc-fd9ddedc900b.png)
This is how it looks without addon enabled

![image](https://user-images.githubusercontent.com/86042561/161904556-ecda85ec-a33e-46eb-9235-d5824e2dd4d1.png)
This is how it looks with addon enabled

**Comment by 0xbs** [comment]
Ah I see! Still, I have the same problem as in #76. I can't fix both #64 and this issue.

Maybe I can check if there is an authenticator attached to your account and disable overwriting of `GetPlaystyleString()` in this case.

**Comment by SuperChronos** [comment]
Ah ok. I'll try the `delete the content of FixGetPlaystyleString.lua (but keep the file)` fix mentioned in #76 or just disable whenever I want to form my own groups

**Comment by 0xbs** [comment]
Yes this would be the intended workaround. I wonder if I can find an automatic solution. There is `C_LFGList.IsPlayerAuthenticatedForLFG(activityID)` which tells if you may create a group for an activity and returns false for current mythic plus dungeons if you do not have an authenticator.

May I ask if the restriction only applies to the current mythic plus content or simply to all premade groups? Does this also apply to other content like PvP, raid or quest groups? Are you allowed to create raid/PvP/quest/torghast/custom groups?

**Comment by 0xbs** [comment]
Kindly have another try with the latest version. I changed the code so that players without an authenticator should be able to use automatic groups titles once again.

**Comment by SuperChronos** [comment]
It is indeed working again! Sorry that I didn't check if its only restricted to m+ or all premades but it does. New update also lets me list PvP and custom groups. Thanks!
