### ISSUE TITLE
[Feature request] Raider IO score Filtering

### ISSUE THREAD

**Issue by alexandrewk** [0xbs/premade-groups-filter#87]
Thank you for this useful addon !
Is there any way to add raider io score filtering or blizzard's mythic + rating ?
I'm not used to addon dev but it would be cool !

**Comment by 0xbs** [comment]
Glad you like it, please have a look at the keywords page:

https://github.com/0xbs/premade-groups-filter/wiki/Keywords#rating

https://github.com/0xbs/premade-groups-filter/wiki/Keywords#raiderio
