### ISSUE TITLE
Interface action failed because of an addon

### ISSUE THREAD

**Issue by jaw98** [0xbs/premade-groups-filter#88]
Using version 2.8.2 I started getting the message

> Interface action failed because of an AddOn

Lua error generated: 
```
1x [ADDON_ACTION_BLOCKED] AddOn 'PremadeGroupsFilter' tried to call the protected function 'GetPlaystyleString()'.
[string "@!BugGrabber\BugGrabber.lua"]:519: in function <!BugGrabber\BugGrabber.lua:519>
[string "=[C]"]: in function `GetPlaystyleString'
[string "@FrameXML\LFGList.lua"]:3515: in function `LFGListUtil_SetSearchEntryTooltip'
[string "@FrameXML\LFGList.lua"]:2579: in function <FrameXML\LFGList.lua:2576>
[string "=[C]"]: ?
```

Possible duplicate of #64 ?

**Comment by 0xbs** [comment]
Do you have an authenticator attached to your account?

Version 2.8.2 reverts the fix for ADDON_ACTION_BLOCKED for players that do not have an authenticator. The reason is that the fix prevents you from creating mythic plus groups with the title automatically set to your keystone level as accounts without authenticator cannot create groups with a custom name (issue #86).

**Comment by jaw98** [comment]
Hmmm, so I do have an authenticator but I just noticed that there is no phone number attached to my account, weird. And I can't create group descriptions even though I do have the authenticator. Will be contacting support to add the phone number back which should then solve the issue.

![image](https://user-images.githubusercontent.com/26303377/162584973-036c9c95-6757-46ca-8f77-399741ac0688.png)

![image](https://user-images.githubusercontent.com/26303377/162584988-b1d3e307-6ec5-4fc4-b4da-a7980f5ed965.png)

So you need SMS and Authenticator it seems.

**Comment by 0xbs** [comment]
Thank you for the insight, this is very helpful. So it is not only the authenticator but also SMS protect. You should see the ADDON_ACTION_BLOCKED error disappear once you fully secured your account (and will hence loose auto-text for new groups).
