### ISSUE TITLE
Double groups in Premade Groups window when appying for group

### ISSUE THREAD

**Issue by Hammerek** [0xbs/premade-groups-filter#91]
Hi, when applying to a group, group state "doubles" itself. For example when I sign up and refresh window the group I applied shows as two same groups. I will provide screenshot so it will be easier to understand. Also I am using ElvUI with Shadow&Light and AddonSkins. I am also using weakauras for M+ but it's maybe not important. The problem itself dissapears when I disable Premade Groups Filer in Premade Group window. 

![image](https://user-images.githubusercontent.com/16039057/166159472-770e5630-8e43-42ad-9a91-cea5f2dbaa62.png)

**Comment by 0xbs** [comment]
Not a PGF issue, please have a look at the first [FAQ entry](https://github.com/0xbs/premade-groups-filter/wiki/FAQ) 🙂

**Comment by Hammerek** [comment]
Oh okay :D Sorry for not reading FAQ. Yes, you are right, same thing happens when I apply  for a group with PGF disabled. 
Temporary workaround worked too! 

I'm closing the issue. :)
