### ISSUE TITLE
New Report Advertisement blocked

### ISSUE THREAD

**Issue by zaphon** [0xbs/premade-groups-filter#95]
Blizzard appears to have hot fixed in a new "Report Advertisement" item right below "Report Group" when you right click on a dungeon group. This eliminates the new nested (multiple clicks) way of reporting groups for advertisement, but for whatever reason, it's being blocked by premade-groups-filter.

I'm not sure there's a way around this or not, but wanted to bring it up either way.

NOTE: The other way (report group) still works, but it requires so many clicks to report a group for advertisement now it's not worth the hassle.

```
1x [ADDON_ACTION_FORBIDDEN] AddOn 'PremadeGroupsFilter' tried to call the protected function 'SendReport()'.
[string "@!BugGrabber\BugGrabber.lua"]:519: in function <!BugGrabber\BugGrabber.lua:519>
[string "=[C]"]: in function `SendReport'
[string "@FrameXML\ReportFrame.lua"]:171: in function `SendReport'
[string "@FrameXML\ReportFrame.lua"]:75: in function `InitiateReportInternal'
[string "@FrameXML\ReportFrame.lua"]:427: in function <FrameXML\ReportFrame.lua:413>
[string "=[C]"]: in function `SetAttribute'
[string "@FrameXML\ReportFrame.lua"]:52: in function `InitiateReport'
[string "@FrameXML\LFGList.lua"]:3281: in function `LFGList_ReportAdvertisement'
[string "@FrameXML\LFGList.lua"]:3313: in function `func'
[string "@SharedXML\UIDropDownMenu.lua"]:918: in function `UIDropDownMenuButton_OnClick'
[string "*:OnClick"]:1: in function <[string "*:OnClick"]:1>
```

![2022-06-16_18-52-18](https://user-images.githubusercontent.com/1243870/174206927-d307014c-e479-4dbd-90f3-aae9c7ed795d.png)

**Comment by 0xbs** [comment]
I can reproduce it, but I do not yet have an idea how to fix it. The taint happens as soon as I remove results from the list.

As a workaround, you can filter those groups quite easily either by `age < 30` or `members > 1` as those groups are usually up for a long time and usually have just one player.

**Comment by zaphon** [comment]
Yeah, most of the time I just use rio > 0 as my filter to get rid of them, but I've been spamming valor runs and those I am looking for someone with no RIO and I'm running with 2 friends, so need to find groups with 1 or 2 people in it. That's why I've been noticing it so much more.

**Comment by xvelezv** [comment]
this is still happening, any fixes?
 `5x [ADDON_ACTION_FORBIDDEN] AddOn 'PremadeGroupsFilter' tried to call the protected function 'SendReport()'.
[string "@!BugGrabber\BugGrabber.lua"]:480: in function <!BugGrabber\BugGrabber.lua:480>
[string "=[C]"]: in function `SendReport'
[string "@FrameXML\ReportFrame.lua"]:171: in function `SendReport'
[string "@FrameXML\ReportFrame.lua"]:75: in function `InitiateReportInternal'
[string "@FrameXML\ReportFrame.lua"]:427: in function <FrameXML\ReportFrame.lua:413>
[string "=[C]"]: in function `SetAttribute'
[string "@FrameXML\ReportFrame.lua"]:52: in function `InitiateReport'
[string "@FrameXML\LFGList.lua"]:3281: in function `LFGList_ReportAdvertisement'
[string "@FrameXML\LFGList.lua"]:3313: in function `func'
[string "@SharedXML\UIDropDownMenu.lua"]:918: in function `UIDropDownMenuButton_OnClick'
[string "*:OnClick"]:1: in function <[string "*:OnClick"]:1>`

**Comment by ChrisKader** [comment]
These taints are almost always caused by using the Blizzard provided `UIDropDownMenu` functions. Highly recommend using [LibUIDropdownMenu](https://www.curseforge.com/wow/addons/libuidropdownmenu) if you have any dropdowns that interact in anyway with code that can become tainted (def the case when working with LFG).

**Comment by 0xbs** [comment]
It's not the dropdown as I'm already using my own dropdown menu. Taints seem to come from modifying the list of premade groups.

**Comment by yourapple** [comment]
It is a temporary solution to allow reporting advertisements to follow the route of reporting teams.
like this
LFGList_ReportAdvertisement = LFGList_ReportListing


Or consider deleting the report ad

**Comment by 0xbs** [comment]
Good suggestion, will consider it.

Link to the semi-official bug tracker: https://github.com/Stanzilla/WoWUIBugs/issues/237
